gcc ^
-g ^
*.c ^
HAN_Lib\*.c ^
Lib\zlib-1.3.1\*.c ^
ToolBox\*.c ^
ToolBox\ConsoleCmd\*.c ^
ToolBox\FileConversion\*.c ^
ToolBox\HexView\*.c ^
ToolBox\BinView\*.c ^
ToolBox\SrecView\*.c ^
ToolBox\AscView\*.c ^
ToolBox\ComTool\*.c ^
ToolBox\ComTool\ComToolModule\GlobalVariables\*.c ^
ToolBox\ComTool\ComToolModule\Console\*.c ^
ToolBox\ComTool\ComToolModule\Graphic\*.c ^
ToolBox\EthernetTool\*.c ^
ToolBox\EthernetTool\EthernetToolModule\GlobalVariables\*.c ^
ToolBox\EthernetTool\EthernetToolModule\Console\*.c ^
ToolBox\EthernetTool\EthernetToolModule\Http\*.c ^
ToolBox\EthernetTool\EthernetToolModule\SomeIP\*.c ^
ToolBox\Picture\*.c ^
ToolBox\Picture\PictureModule\ICCProfile\*.c ^
ToolBox\Picture\PictureModule\EditTool\*.c ^
ToolBox\Picture\PictureModule\Icon\*.c ^
ToolBox\Picture\PictureModule\BitMap\*.c ^
ToolBox\Picture\PictureModule\Png\*.c ^
ToolBox\Picture\PictureModule\Jpeg\*.c ^
ToolBox\Picture\PictureModule\Jpeg\GlobalVariables\*.c ^
ToolBox\Picture\PictureModule\Jpeg\MCUView\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\IFD\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\IPTC\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\MakerNote\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\MakerNote\Sony\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\APP0\JFIF\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\APP1\Exif\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\APP1\XMP\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\APP2\MPF\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\APP2\ICCProfile\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\APP13\Photoshop\*.c ^
ToolBox\Picture\PictureModule\Jpeg\APP\APP14\Adobe\*.c ^
ToolBox\Video\*.c ^
ToolBox\Video\VideoModule\MP4\*.c ^
ToolBox\Video\VideoModule\H264\*.c ^
-lgdi32 ^
-lcomdlg32 ^
-lcomctl32 ^
-lshlwapi ^
-lwsock32 ^
-liphlpapi ^
-lwinhttp ^
-lws2_32 ^
-Wall -Wextra ^
-o ToolBox.exe

ToolBox.exe
