#ifndef HAN_PICTURE_EDIT_TOOL_DEF_H
#define HAN_PICTURE_EDIT_TOOL_DEF_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <Windows.h>

#include "..\..\HAN_PictureDef.h"

#define HAN_PICTURE_EDIT_TOOL_TEXT_BUF_SIZE         1024

#define HAN_PICTURE_EDIT_TOOL_PAINT_MIN_W           1000
#define HAN_PICTURE_EDIT_TOOL_PAINT_MIN_H           500

#define HAN_PICTURE_EDIT_TOOL_PAINT_SCROLL_WIDTH    15
#define HAN_PICTURE_EDIT_TOOL_PAINT_SCROLL_UNIT     2

#define PICTURE_EDIT_TOOL_CONSOLE_WIDTH             300

#define HAN_PICTURE_EDIT_TOOL_MIN_W                 (HAN_PICTURE_EDIT_TOOL_PAINT_MIN_W + PICTURE_WINDOW_DX + PICTURE_EDIT_TOOL_CONSOLE_WIDTH)
#define HAN_PICTURE_EDIT_TOOL_MIN_H                 (HAN_PICTURE_EDIT_TOOL_PAINT_MIN_H)

#define PICTURE_EDIT_TOOL_ZOOM_EDIT_WIDTH           100
#define PICTURE_EDIT_TOOL_ZOOM_EDIT_HEIGHT          25
#define PICTURE_EDIT_TOOL_ZOOM_OPTION_HEIGHT        25

#define PICTURE_EDIT_TOOL_BACKGROUND_COLOR          RGB(0x40, 0x40, 0x40)

#define PICTURE_EDIT_TOOL_ALPHA_BG_SIZE             8

#define PICTURE_EDIT_TOOL_CONSOLE_SETTING_TEXT_W    60
#define PICTURE_EDIT_TOOL_CONSOLE_SETTING_TEXT_H    16
#define PICTURE_EDIT_TOOL_CONSOLE_BAR_H             20

typedef enum {
    PETM_NOTUSED = PCTM_MODELBASE,      // 不使用的消息值，自定义消息请在下方添加
    PETM_SETPAINTID,                    // 设置需要绘制的图片 ID（WPARAM：从 0 开始的图片 ID，LPARAM：未使用，return：是否成功）
    PETM_GETPAINTID,                    // 获取当前激活的图片 ID（WPARAM：未使用，LPARAM：未使用，return：从 0 开始的图片 ID）
} PICTUREEDITTOOLMESSAGE;

typedef enum {
    PICTURE_EDIT_TOOL_ZOOM_001250,
    PICTURE_EDIT_TOOL_ZOOM_002500,
    PICTURE_EDIT_TOOL_ZOOM_005000,
    PICTURE_EDIT_TOOL_ZOOM_010000,
    PICTURE_EDIT_TOOL_ZOOM_020000,
    PICTURE_EDIT_TOOL_ZOOM_030000,
    PICTURE_EDIT_TOOL_ZOOM_040000,
    PICTURE_EDIT_TOOL_ZOOM_050000,
    PICTURE_EDIT_TOOL_ZOOM_100000,
    PICTURE_EDIT_TOOL_ZOOM_CNT,
} PICTUREEDITTOOLZOOM;

#ifdef __cplusplus
}
#endif

#endif
