#ifndef HAN_PICTURE_JPEG_GLOBAL_VARIABLES_H
#define HAN_PICTURE_JPEG_GLOBAL_VARIABLES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "..\HAN_PictureJpegMath.h"
#include "..\HAN_PictureJpegSegment.h"

typedef enum {
    PICTURE_SAVE_JPEG_QUANTIZATION_TABLE_DEFAULT,
    PICTURE_SAVE_JPEG_QUANTIZATION_TABLE_HIGH,
    PICTURE_SAVE_JPEG_QUANTIZATION_TABLE_CNT,
} PICTURESAVEJPEGQUANTIZATIONTABLE;

typedef enum {
    PICTURE_SAVE_JPEG_HUFFMAN_TABLE_BASELINE_DEFAULT,
    PICTURE_SAVE_JPEG_HUFFMAN_TABLE_PROGRESSIVE_DEFAULT,
    PICTURE_SAVE_JPEG_HUFFMAN_TABLE_CNT,
} PICTURESAVEJPEGHUFFMANTABLE;

typedef struct tagPICTURESAVEJPEGQUANTIZATIONTABLEINFO {
    const PICTUREJPEGDCTMATRIX2D*   pQuantization;
    HANSIZE                         nCnt;
} PICTURESAVEJPEGQUANTIZATIONTABLEINFO, * PPICTURESAVEJPEGQUANTIZATIONTABLEINFO;
typedef const PICTURESAVEJPEGQUANTIZATIONTABLEINFO* PCPICTURESAVEJPEGQUANTIZATIONTABLEINFO;

typedef struct tagPICTURESAVEJPEGHUFFMANTABLEINFO {
    PCPICTUREJPEGSEGMENTDHTINFO     pHuffman[PICTURE_JPEG_SEGMENT_DHT_TABLE_TYPE_CNT][PICTURE_JPEG_SEGMENT_HT_MAX];
    HANSIZE                         nCnt[PICTURE_JPEG_SEGMENT_DHT_TABLE_TYPE_CNT];
} PICTURESAVEJPEGHUFFMANTABLEINFO, * PPICTURESAVEJPEGHUFFMANTABLEINFO;
typedef const PICTURESAVEJPEGHUFFMANTABLEINFO* PCPICTURESAVEJPEGHUFFMANTABLEINFO;

extern const PICTURESAVEJPEGQUANTIZATIONTABLEINFO g_pSaveJpegQuantizationTable[PICTURE_SAVE_JPEG_QUANTIZATION_TABLE_CNT];

extern const PICTURESAVEJPEGHUFFMANTABLEINFO g_pSaveJpegHuffmanTableInfo[PICTURE_SAVE_JPEG_HUFFMAN_TABLE_CNT];

#ifdef __cplusplus
}
#endif

#endif
