#include "HAN_PictureJpegSegment.h"

#if 1 /******************** default ********************/
static const HANPSTR sg_pJpeg_Default_Name = TEXT("不支持该数据段");
static const HANPSTR sg_pJpegSegmentFieldName_Default[PICTURE_JPEG_DEFAULT_SEGMENT_FIELD_CNT] = {
    [PICTURE_JPEG_DEFAULT_SEGMENT_FIELD_LEN] = TEXT("长度"),
    [PICTURE_JPEG_DEFAULT_SEGMENT_FIELD_DATA] = TEXT("数据"),
    [PICTURE_JPEG_DEFAULT_SEGMENT_FIELD_EXLEN] = TEXT("附加长度"),
    [PICTURE_JPEG_DEFAULT_SEGMENT_FIELD_EXDATA] = TEXT("附加数据"),
};

HANPSTR GetJpeg_Default_Name(void)
{
    return sg_pJpeg_Default_Name;
}
HANPSTR GetJpeg_Default_FieldName(PICTUREJPEGSEGMENTFIELD_DEFAULT eName)
{
    return sg_pJpegSegmentFieldName_Default[eName];
}
#endif

#if 1 /******************** SOI ********************/
static const HANPSTR sg_pJpeg_SOI_Name = TEXT("文件头");

HANPSTR GetJpeg_SOI_Name(void)
{
    return sg_pJpeg_SOI_Name;
}
#endif

#if 1 /******************** APP0 ********************/
typedef enum {
    PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_0,
    PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_1,
    PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_2,
    PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_DEFAULT,
    PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_CNT,
} PICTUREJPEGAPP0SEGMENTFIELDDENSITYUNIT;

static const HANPSTR sg_pJpeg_APP0_Name = TEXT("APP0");
static const HANPSTR sg_pJpegSegmentFieldName_APP0[PICTURE_JPEG_APP0_SEGMENT_FIELD_CNT] = {
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_VERSION] = TEXT("版本号"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT] = TEXT("密度单位"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_X_DENSITY] = TEXT("X像素密度"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_Y_DENSITY] = TEXT("Y像素密度"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_THUMB_X_PIXEL] = TEXT("缩略图X像素"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_THUMB_Y_PIXEL] = TEXT("缩略图Y像素"),
};
static const HANPSTR sg_pJpeg_APP0_DensityUnitName[PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_CNT] = {
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_0] = TEXT("无单位"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_1] = TEXT("点 / 英寸"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_2] = TEXT("点 / 厘米"),
    [PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_DEFAULT] = TEXT("未知单位"),
};

HANPSTR GetJpeg_APP0_Name(void)
{
    return sg_pJpeg_APP0_Name;
}
HANPSTR GetJpeg_APP0_FieldName(PICTUREJPEGSEGMENTFIELD_APP0 eName)
{
    return sg_pJpegSegmentFieldName_APP0[eName];
}
HANPSTR GetJpeg_APP0_DensityUnitName(uint8_t cUnit)
{
    HANPSTR pRet;

    switch (cUnit) {
        case 0: { pRet = sg_pJpeg_APP0_DensityUnitName[PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_0]; } break;
        case 1: { pRet = sg_pJpeg_APP0_DensityUnitName[PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_1]; } break;
        case 2: { pRet = sg_pJpeg_APP0_DensityUnitName[PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_2]; } break;
        default: { pRet = sg_pJpeg_APP0_DensityUnitName[PICTURE_JPEG_APP0_SEGMENT_FIELD_DENSITY_UNIT_DEFAULT]; } break;
    }

    return pRet;
}
#endif

#if 1 /******************** APP1 ********************/
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDCOMPRESSION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_8,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_9,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_10,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32803,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32844,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32845,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32892,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_34892,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_51177,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_52527,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDPHOTOMETRICINTERPRETATION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_7,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_8,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDORIENTATION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDRESOLUTIONUNIT;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDYCBCRPOSITION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_7,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_8,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDEXPOSUREPROGRAM;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_7,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDSENSITIVITYTYPE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDCOMPONENTCONFIGURATION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_255,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDMETERINGMODE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_9,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_10,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_11,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_12,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_13,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_14,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_15,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_16,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_17,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_18,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_19,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_20,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_21,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_22,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_23,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_24,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_255,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDLIGHTSOURCE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFLASHFIRED;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_00,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_01,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_10,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_11,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFLASHRETURN;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_00,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_01,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_10,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_11,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFLASHMODE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFLASHFUNCTION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFLASHREDEYEMODE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_0100,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFLASHPIXVERSION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDCOLORSPACE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFOCALPLANERESOLUTIONUNIT;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_7,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_8,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDSENSINGMETHOD;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDFILESOURCE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDSCENETYPE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_5,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_6,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDCFAPATTERN;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDCUSTOMRENDERED;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDEXPOSUREMODE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDWHITEBALANCE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDSCENECAPTURETYPE;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_4,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDGAINCONTROL;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDCONTRAST;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDSATURATION;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDSHARPNESS;
typedef enum {
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_0,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_1,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_2,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_3,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_DEFAULT,
    PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_CNT,
} PICTUREJPEGAPP1SEGMENTFIELDSUBJECT_DISTANCE_RANGE;

typedef struct tagPICTUREJPEGIFDSEGMENTFIELDNAMEINFO {
    uint16_t    nIFDId;
    HANSIZE     nMemberId;
    PCCH        pExifName;
    HANPSTR     pTitle;
} PICTUREJPEGIFDSEGMENTFIELDNAMEINFO;

static const HANPSTR sg_pJpeg_APP1_Name = TEXT("APP1");
static const PICTUREJPEGIFDSEGMENTFIELDNAMEINFO sg_pJpegSegmentFieldName_APP1[PICTURE_JPEG_APP1_SEGMENT_FIELD_CNT] = {
#if 1 /* Exif */
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_INTEROPERABILITY_INDEX] = {
        .nIFDId = 0x0001,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("IOP编号"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_INTEROPERABILITY_VERSION] = {
        .nIFDId = 0x0002,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("IOP版本"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_IMAGE_WIDTH] = {
        .nIFDId = 0x0100,
        .nMemberId = 0,
        .pExifName = "ImageWidth",
        .pTitle = TEXT("图像宽度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_IMAGE_HEIGHT] = {
        .nIFDId = 0x0101,
        .nMemberId = 0,
        .pExifName = "ImageLength",
        .pTitle = TEXT("图像高度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_BITS_PER_SAMPLE] = {
        .nIFDId = 0x0102,
        .nMemberId = 0,
        .pExifName = "BitsPerSample",
        .pTitle = TEXT("通道位数"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION] = {
        .nIFDId = 0x0103,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("压缩格式"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION] = {
        .nIFDId = 0x0106,
        .nMemberId = 0,
        .pExifName = "PhotometricInterpretation",
        .pTitle = TEXT("光度解释"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_IMAGE_DESCRIPTION] = {
        .nIFDId = 0x010E,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("图像描述"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CAMERA_MAKE] = {
        .nIFDId = 0x010F,
        .nMemberId = 0,
        .pExifName = "Make",
        .pTitle = TEXT("相机制造商"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CAMERA_MODEL] = {
        .nIFDId = 0x0110,
        .nMemberId = 0,
        .pExifName = "Model",
        .pTitle = TEXT("相机型号"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION] = {
        .nIFDId = 0x0112,
        .nMemberId = 0,
        .pExifName = "Orientation",
        .pTitle = TEXT("旋转位置"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SAMPLES_PER_PIXEL] = {
        .nIFDId = 0x0115,
        .nMemberId = 0,
        .pExifName = "SamplesPerPixel",
        .pTitle = TEXT("分量数"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_H] = {
        .nIFDId = 0x011A,
        .nMemberId = 0,
        .pExifName = "XResolution",
        .pTitle = TEXT("水平分辨率"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_V] = {
        .nIFDId = 0x011B,
        .nMemberId = 0,
        .pExifName = "YResolution",
        .pTitle = TEXT("垂直分辨率"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT] = {
        .nIFDId = 0x0128,
        .nMemberId = 0,
        .pExifName = "ResolutionUnit",
        .pTitle = TEXT("分辨率单位"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SOFTWARE] = {
        .nIFDId = 0x0131,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("软件"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_DATETIME] = {
        .nIFDId = 0x0132,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("编辑时间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_POINT] = {
        .nIFDId = 0x013E,
        .nMemberId = 0,
        .pExifName = "WhitePoint",
        .pTitle = TEXT("白点"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PRIMARY_CHROMATICITIES] = {
        .nIFDId = 0x013F,
        .nMemberId = 0,
        .pExifName = "PrimaryChromaticities",
        .pTitle = TEXT("原始色度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_THUMB_POS] = {
        .nIFDId = 0x0201,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("缩略图位置"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_THUMB_SIZE] = {
        .nIFDId = 0x0202,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("缩略图大小"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_COEFFICIENTS] = {
        .nIFDId = 0x0211,
        .nMemberId = 0,
        .pExifName = "YCbCrCoefficients",
        .pTitle = TEXT("YCbCr转换系数"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION] = {
        .nIFDId = 0x0213,
        .nMemberId = 0,
        .pExifName = "YCbCrPositioning",
        .pTitle = TEXT("YCbCr对齐方式"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RELATED_IMAGE_WIDTH] = {
        .nIFDId = 0x1001,
        .nMemberId = 0,
        .pExifName = "RelatedImageWidth",
        .pTitle = TEXT("相关图像宽度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RELATED_IMAGE_HEIGHT] = {
        .nIFDId = 0x1002,
        .nMemberId = 0,
        .pExifName = "RelatedImageHeight",
        .pTitle = TEXT("相关图像高度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COPY_RIGHT] = {
        .nIFDId = 0x8298,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("版权"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_TIME] = {
        .nIFDId = 0x829A,
        .nMemberId = 0,
        .pExifName = "ExposureTime",
        .pTitle = TEXT("曝光时间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_F_NUMBER] = {
        .nIFDId = 0x829D,
        .nMemberId = 0,
        .pExifName = "FNumber",
        .pTitle = TEXT("光圈值"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM] = {
        .nIFDId = 0x8822,
        .nMemberId = 0,
        .pExifName = "ExposureProgram",
        .pTitle = TEXT("曝光程序"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ISO_SPEED] = {
        .nIFDId = 0x8827,
        .nMemberId = 0,
        .pExifName = "ISOSpeedRatings",
        .pTitle = TEXT("ISO速度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE] = {
        .nIFDId = 0x8830,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("感光类型"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_REI] = {
        .nIFDId = 0x8832,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("推荐曝光指数"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXIF_VERSION] = {
        .nIFDId = 0x9000,
        .nMemberId = 0,
        .pExifName = "ExifVersion",
        .pTitle = TEXT("Exif版本"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_DATETIME_ORI] = {
        .nIFDId = 0x9003,
        .nMemberId = 0,
        .pExifName = "DateTimeOriginal",
        .pTitle = TEXT("拍摄时间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_DATETIME_DIGIT] = {
        .nIFDId = 0x9004,
        .nMemberId = 0,
        .pExifName = "DateTimeDigitized",
        .pTitle = TEXT("数字化时间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION] = {
        .nIFDId = 0x9101,
        .nMemberId = 0,
        .pExifName = "ComponentsConfiguration",
        .pTitle = TEXT("颜色顺序"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSED_BITS_PER_PIXEL] = {
        .nIFDId = 0x9102,
        .nMemberId = 0,
        .pExifName = "CompressedBitsPerPixel",
        .pTitle = TEXT("压缩位/像素"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SHUTTER_SPEED_VALUE] = {
        .nIFDId = 0x9201,
        .nMemberId = 0,
        .pExifName = "ShutterSpeedValue",
        .pTitle = TEXT("快门速度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_APERTURE_VALUE] = {
        .nIFDId = 0x9202,
        .nMemberId = 0,
        .pExifName = "ApertureValue",
        .pTitle = TEXT("光圈"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_BRIGHTNESS] = {
        .nIFDId = 0x9203,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("场景亮度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_BIAS] = {
        .nIFDId = 0x9204,
        .nMemberId = 0,
        .pExifName = "ExposureBiasValue",
        .pTitle = TEXT("曝光补偿"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_MAX_APERTURE] = {
        .nIFDId = 0x9205,
        .nMemberId = 0,
        .pExifName = "MaxApertureValue",
        .pTitle = TEXT("最大光圈"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE] = {
        .nIFDId = 0x9207,
        .nMemberId = 0,
        .pExifName = "MeteringMode",
        .pTitle = TEXT("测光模式"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE] = {
        .nIFDId = 0x9208,
        .nMemberId = 0,
        .pExifName = "LightSource",
        .pTitle = TEXT("光源"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED] = {
        .nIFDId = 0x9209,
        .nMemberId = 0,
        .pExifName = "Fired",
        .pTitle = TEXT("闪光灯-触发"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN] = {
        .nIFDId = 0x9209,
        .nMemberId = 0,
        .pExifName = "Return",
        .pTitle = TEXT("闪光灯-回光检测"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE] = {
        .nIFDId = 0x9209,
        .nMemberId = 0,
        .pExifName = "Mode",
        .pTitle = TEXT("闪光灯-模式"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION] = {
        .nIFDId = 0x9209,
        .nMemberId = 0,
        .pExifName = "Function",
        .pTitle = TEXT("闪光灯-功能"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE] = {
        .nIFDId = 0x9209,
        .nMemberId = 0,
        .pExifName = "RedEyeMode",
        .pTitle = TEXT("闪光灯-防红眼"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_LENGTH] = {
        .nIFDId = 0x920A,
        .nMemberId = 0,
        .pExifName = "FocalLength",
        .pTitle = TEXT("焦距"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_USER_COMMENT] = {
        .nIFDId = 0x9286,
        .nMemberId = 0,
        .pExifName = "UserComment",
        .pTitle = TEXT("用户注释"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUB_SEC_TIME] = {
        .nIFDId = 0x9290,
        .nMemberId = 0,
        .pExifName = "SubSecTime",
        .pTitle = TEXT("亚秒编辑时间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUB_SEC_TIME_ORI] = {
        .nIFDId = 0x9291,
        .nMemberId = 0,
        .pExifName = "SubSecTimeOriginal",
        .pTitle = TEXT("亚秒拍摄时间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUB_SEC_TIME_DIGIT] = {
        .nIFDId = 0x9292,
        .nMemberId = 0,
        .pExifName = "SubSecTimeDigitized",
        .pTitle = TEXT("亚秒数字化时间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION] = {
        .nIFDId = 0xA000,
        .nMemberId = 0,
        .pExifName = "FlashpixVersion",
        .pTitle = TEXT("FlashPix版本"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE] = {
        .nIFDId = 0xA001,
        .nMemberId = 0,
        .pExifName = "ColorSpace",
        .pTitle = TEXT("色彩空间"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_WIDTH] = {
        .nIFDId = 0xA002,
        .nMemberId = 0,
        .pExifName = "PixelXDimension",
        .pTitle = TEXT("图像宽度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_HEIGHT] = {
        .nIFDId = 0xA003,
        .nMemberId = 0,
        .pExifName = "PixelYDimension",
        .pTitle = TEXT("图像高度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD] = {
        .nIFDId = 0xA217,
        .nMemberId = 0,
        .pExifName = "SensingMethod",
        .pTitle = TEXT("感应方式"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_X_RESOLUTION] = {
        .nIFDId = 0xA217,
        .nMemberId = 0,
        .pExifName = "SensingMethod",
        .pTitle = TEXT("焦平面水平分辨率"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_Y_RESOLUTION] = {
        .nIFDId = 0xA217,
        .nMemberId = 0,
        .pExifName = "SensingMethod",
        .pTitle = TEXT("焦平面垂直分辨率"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT] = {
        .nIFDId = 0xA217,
        .nMemberId = 0,
        .pExifName = "SensingMethod",
        .pTitle = TEXT("焦平面分辨率单位"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE] = {
        .nIFDId = 0xA300,
        .nMemberId = 0,
        .pExifName = "FileSource",
        .pTitle = TEXT("图像来源"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE] = {
        .nIFDId = 0xA301,
        .nMemberId = 0,
        .pExifName = "SceneType",
        .pTitle = TEXT("拍摄场景类型"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN] = {
        .nIFDId = 0xA302,
        .nMemberId = 0,
        .pExifName = "CFAPattern",
        .pTitle = TEXT("色彩滤波阵列图案"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_RENDERED] = {
        .nIFDId = 0xA401,
        .nMemberId = 0,
        .pExifName = "CustomRendered",
        .pTitle = TEXT("自定义处理"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE] = {
        .nIFDId = 0xA402,
        .nMemberId = 0,
        .pExifName = "ExposureMode",
        .pTitle = TEXT("曝光模式"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE] = {
        .nIFDId = 0xA403,
        .nMemberId = 0,
        .pExifName = "WhiteBalance",
        .pTitle = TEXT("白平衡"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_DIGITAL_ZOOM_RATIO] = {
        .nIFDId = 0xA404,
        .nMemberId = 0,
        .pExifName = "DigitalZoomRatio",
        .pTitle = TEXT("数码变焦倍率"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_LENGTH_IN_35MM_FILM] = {
        .nIFDId = 0xA405,
        .nMemberId = 0,
        .pExifName = "FocalLengthIn35mmFilm",
        .pTitle = TEXT("35mm焦距"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE] = {
        .nIFDId = 0xA406,
        .nMemberId = 0,
        .pExifName = "SceneCaptureType",
        .pTitle = TEXT("场景类型"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL] = {
        .nIFDId = 0xA407,
        .nMemberId = 0,
        .pExifName = "GainControl",
        .pTitle = TEXT("增益控制"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST] = {
        .nIFDId = 0xA408,
        .nMemberId = 0,
        .pExifName = "Contrast",
        .pTitle = TEXT("对比度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION] = {
        .nIFDId = 0xA409,
        .nMemberId = 0,
        .pExifName = "Saturation",
        .pTitle = TEXT("饱和度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS] = {
        .nIFDId = 0xA40A,
        .nMemberId = 0,
        .pExifName = "Sharpness",
        .pTitle = TEXT("锐度"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE] = {
        .nIFDId = 0xA40C,
        .nMemberId = 0,
        .pExifName = "SubjectDistanceRange",
        .pTitle = TEXT("拍摄物体距离范围"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LENS_INFO] = {
        .nIFDId = 0xA432,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("镜头信息"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_MIN_FOCAL] = {
        .nIFDId = 0xA432,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("最小焦距"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_MAX_FOCAL] = {
        .nIFDId = 0xA432,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("最大焦距"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_MIN_FOCAL_MAX_APERTURE] = {
        .nIFDId = 0xA432,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("最小焦距下最大光圈"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_MAX_FOCAL_MAX_APERTURE] = {
        .nIFDId = 0xA432,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("最大焦距下最大光圈"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LENS_MODEL] = {
        .nIFDId = 0xA434,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("镜头型号"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAMMA] = {
        .nIFDId = 0xA500,
        .nMemberId = 0,
        .pExifName = "Gamma",
        .pTitle = TEXT("Gamma值"),
    },
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PRINT_IM] = {
        .nIFDId = 0xC4A5,
        .nMemberId = 0,
        .pExifName = "",
        .pTitle = TEXT("PrintIM"),
    },
#endif
#if 1 /* GPS */
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GPS_VERSION_ID] = {
        .nIFDId = 0x0000,
        .nMemberId = 0,
        .pExifName = "GPSVersionID",
        .pTitle = TEXT("GPS版本号"),
    },
#endif
};
static const HANPSTR sg_pJpeg_APP1_CompressionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_1] = TEXT("未压缩"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_6] = TEXT("JPEG压缩格式"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_DEFAULT] = TEXT("不支持"),
};
static const HANPSTR sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_0] = TEXT("灰度图，0代表白色"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_1] = TEXT("灰度图，0代表黑色"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_2] = TEXT("RGB真彩色图像"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_3] = TEXT("调色板图像"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_4] = TEXT("透明蒙版图"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_5] = TEXT("CMYK"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_6] = TEXT("YCbCr"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_8] = TEXT("CIE Lab"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_9] = TEXT("ICC Lab"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_10] = TEXT("ITU Lab"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32803] = TEXT("CFA色彩滤波阵列"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32844] = TEXT("Pixar LogL"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32845] = TEXT("Pixar LogLuv"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32892] = TEXT("时序滤色器"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_34892] = TEXT("线性化原始数据"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_51177] = TEXT("深度图"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_52527] = TEXT("语义蒙版"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_DEFAULT] = TEXT("未知"),
};
static const HANPSTR sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_1] = TEXT("未翻转"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_2] = TEXT("水平翻转"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_3] = TEXT("180°旋转"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_4] = TEXT("垂直翻转"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_5] = TEXT("顺时针90°+水平翻转"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_6] = TEXT("顺时针90°"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_7] = TEXT("顺时针90°+垂直翻转"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_8] = TEXT("逆时针90°"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_DEFAULT] = TEXT("无效值"),
};
static const HANPSTR sg_pJpeg_APP1_ResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_1] = TEXT("无单位"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_2] = TEXT("英寸"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_3] = TEXT("厘米"),
};
static const HANPSTR sg_pJpeg_APP1_YCbCrPositionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_1] = TEXT("居中"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_2] = TEXT("同位"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_1] = TEXT("手动曝光"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_2] = TEXT("自动曝光"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_3] = TEXT("光圈优先"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_4] = TEXT("速度优先"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_5] = TEXT("慢速模式"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_6] = TEXT("运动模式"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_7] = TEXT("肖像模式"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_8] = TEXT("风景模式"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_1] = TEXT("SOS"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_2] = TEXT("REI"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_3] = TEXT("ISO"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_4] = TEXT("SOS & REI"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_5] = TEXT("SOS & ISO"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_6] = TEXT("REI & ISO"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_7] = TEXT("SOS & REI & ISO"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_DEFAULT] = TEXT("未知"),
};
static const HANPSTR sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_1] = TEXT("Y"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_2] = TEXT("Cb"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_3] = TEXT("Cr"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_4] = TEXT("R"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_5] = TEXT("G"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_6] = TEXT("B"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_DEFAULT] = TEXT("None"),
};
static const HANPSTR sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_DEFAULT] = TEXT("未知"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_1] = TEXT("平均"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_2] = TEXT("中央"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_3] = TEXT("点"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_4] = TEXT("多点"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_5] = TEXT("多区域"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_6] = TEXT("部分"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_255] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_DEFAULT] = TEXT("未知"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_1] = TEXT("曝光"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_2] = TEXT("荧光灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_3] = TEXT("白炽灯（钨丝）"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_4] = TEXT("闪光灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_9] = TEXT("晴天"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_10] = TEXT("阴天"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_11] = TEXT("阴影"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_12] = TEXT("日光灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_13] = TEXT("日光白色荧光灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_14] = TEXT("冷白色荧光灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_15] = TEXT("白色荧光灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_16] = TEXT("暖白色荧光灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_17] = TEXT("标准光A"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_18] = TEXT("标准光B"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_19] = TEXT("标准光C"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_20] = TEXT("D55"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_21] = TEXT("D65"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_22] = TEXT("D75"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_23] = TEXT("D50"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_24] = TEXT("ISO工作室钨丝灯"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_255] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_FlashFiredName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_0] = TEXT("未触发"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_1] = TEXT("触发"),
};
static const HANPSTR sg_pJpeg_APP1_FlashReturnName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_00] = TEXT("无回光检测功能"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_01] = TEXT("未知"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_10] = TEXT("无反射"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_11] = TEXT("有反射"),
};
static const HANPSTR sg_pJpeg_APP1_FlashModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_00] = TEXT("未知模式"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_01] = TEXT("强制开启"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_10] = TEXT("强制关闭"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_11] = TEXT("自动闪光"),
};
static const HANPSTR sg_pJpeg_APP1_FlashFunctionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_0] = TEXT("有闪光灯功能"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_1] = TEXT("无闪光灯功能"),
};
static const HANPSTR sg_pJpeg_APP1_FlashRedEyeModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_0] = TEXT("关闭"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_1] = TEXT("开启"),
};
static const HANPSTR sg_pJpeg_APP1_FlashPixVersionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_0100] = TEXT("1.0"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_ColorSpaceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_1] = TEXT("sRGB"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_2] = TEXT("Adobe RGB"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_FocalPlaneResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_1] = TEXT("无"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_2] = TEXT("英寸"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_3] = TEXT("厘米"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_4] = TEXT("毫米"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_5] = TEXT("微米"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_1] = TEXT("未定义"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_2] = TEXT("单片式彩色区域传感器"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_3] = TEXT("双片式彩色区域传感器"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_4] = TEXT("三片式彩色区域传感器"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_5] = TEXT("色彩顺序区域传感器"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_7] = TEXT("三线性传感器"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_8] = TEXT("色彩顺序线性传感器"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_FileSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_1] = TEXT("胶片扫描仪"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_2] = TEXT("反射式打印扫描仪"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_3] = TEXT("数字相机"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_DEFAULT] = TEXT("未知"),
};
static const HANPSTR sg_pJpeg_APP1_SceneTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_1] = TEXT("直接拍摄"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_0] = TEXT("红"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_1] = TEXT("绿"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_2] = TEXT("蓝"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_3] = TEXT("青"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_4] = TEXT("品"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_5] = TEXT("黄"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_6] = TEXT("白"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_DEFAULT] = TEXT("×"),
};
static const HANPSTR sg_pJpeg_APP1_CustomRenderedName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_0] = TEXT("标准处理"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_1] = TEXT("自定义处理"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_ExposureModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_0] = TEXT("自动曝光"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_1] = TEXT("手动曝光"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_2] = TEXT("自动包围曝光"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_DEFAULT] = TEXT("未知"),
};
static const HANPSTR sg_pJpeg_APP1_WhiteBalanceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_0] = TEXT("自动平衡"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_1] = TEXT("手动平衡"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_DEFAULT] = TEXT("未知"),
};
static const HANPSTR sg_pJpeg_APP1_SceneCaptureTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_0] = TEXT("标准"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_1] = TEXT("风景"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_2] = TEXT("人像"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_3] = TEXT("夜景"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_DEFAULT] = TEXT("未知"),
};
static const HANPSTR sg_pJpeg_APP1_GainControlName[PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_0] = TEXT("无增益"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_1] = TEXT("低增益提升"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_2] = TEXT("高增益提升"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_3] = TEXT("低增益降低"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_4] = TEXT("高增益降低"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_DEFAULT] = TEXT("未知"),
};
static const HANPSTR sg_pJpeg_APP1_ContrastName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_0] = TEXT("标准"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_1] = TEXT("低"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_2] = TEXT("高"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_SaturationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_0] = TEXT("标准"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_1] = TEXT("低"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_2] = TEXT("高"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_SharpnessName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_0] = TEXT("标准"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_1] = TEXT("柔和"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_2] = TEXT("强烈"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_DEFAULT] = TEXT("其他"),
};
static const HANPSTR sg_pJpeg_APP1_SubjectDistanceRangeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_CNT] = {
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_0] = TEXT("未知"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_1] = TEXT("微距"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_2] = TEXT("近景"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_3] = TEXT("远景"),
    [PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_DEFAULT] = TEXT("其它"),
};

HANPSTR GetJpeg_APP1_Name(void)
{
    return sg_pJpeg_APP1_Name;
}
HANPSTR GetJpeg_APP1_FieldName(PICTUREJPEGSEGMENTFIELD_APP1 eName)
{
    return sg_pJpegSegmentFieldName_APP1[eName].pTitle;
}
HANPSTR GetJpeg_APP1_FieldNameByExifName(PCCH pExifName)
{
    HANPSTR pRet = NULL;

    for (PICTUREJPEGSEGMENTFIELD_APP1 iLoop = 0; iLoop < PICTURE_JPEG_APP1_SEGMENT_FIELD_CNT; iLoop++)
    {
        if (!_stricmp(pExifName, sg_pJpegSegmentFieldName_APP1[iLoop].pExifName))
        {
            pRet = sg_pJpegSegmentFieldName_APP1[iLoop].pTitle;
        }
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FieldNameByTIFFName(PCCH pTIFFName)
{
    return GetJpeg_APP1_FieldNameByExifName(pTIFFName);
}
HANPSTR GetJpeg_APP1_CompressionName(uint16_t cCompression)
{
    HANPSTR pRet;

    switch (cCompression) {
        case 1: { pRet = sg_pJpeg_APP1_CompressionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_1]; } break;
        case 6: { pRet = sg_pJpeg_APP1_CompressionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_6]; } break;
        default: { pRet = sg_pJpeg_APP1_CompressionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPRESSION_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_PhotometricInterpretationName(uint16_t cPI)
{
    HANPSTR pRet;

    switch (cPI) {
        case 0: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_5]; } break;
        case 6: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_6]; } break;
        case 8: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_8]; } break;
        case 9: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_9]; } break;
        case 10: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_10]; } break;
        case 32803: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32803]; } break;
        case 32844: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32844]; } break;
        case 32845: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32845]; } break;
        case 32892: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_32892]; } break;
        case 34892: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_34892]; } break;
        case 51177: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_51177]; } break;
        case 52527: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_52527]; } break;
        default: { pRet = sg_pJpeg_APP1_PhotometricInterpretationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_PHOTOMETRIC_INTERPRETATION_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_OrientationName(uint16_t cOrientation)
{
    HANPSTR pRet;

    switch (cOrientation) {
        case 1: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_5]; } break;
        case 6: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_6]; } break;
        case 7: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_7]; } break;
        case 8: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_8]; } break;
        default: { pRet = sg_pJpeg_APP1_OrientationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_ORIENTATION_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_ResolutionUnitName(uint16_t cUnit)
{
    HANPSTR pRet;

    switch (cUnit) {
        case 1: { pRet = sg_pJpeg_APP1_ResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_ResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_ResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_3]; } break;
        default: { pRet = sg_pJpeg_APP1_ResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_RESOLUTION_UNIT_3]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_YCbCrositionName(uint16_t cPosition)
{
    HANPSTR pRet;

    switch (cPosition) {
        case 1: { pRet = sg_pJpeg_APP1_YCbCrPositionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_YCbCrPositionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_2]; } break;
        default: { pRet = sg_pJpeg_APP1_YCbCrPositionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_YCBCR_POSITION_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_ExposureProgramName(uint16_t cExposureProgram)
{
    HANPSTR pRet;

    switch (cExposureProgram) {
        case 1: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_5]; } break;
        case 6: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_6]; } break;
        case 7: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_7]; } break;
        case 8: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_8]; } break;
        default: { pRet = sg_pJpeg_APP1_ExposureProgramName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_PROGRAM_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_SensitivityTypeName(uint16_t cType)
{
    HANPSTR pRet;

    switch (cType) {
        case 1: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_5]; } break;
        case 6: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_6]; } break;
        case 7: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_7]; } break;
        default: { pRet = sg_pJpeg_APP1_SensitivityTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSITIVITY_TYPE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_ComponentConfigurationName(uint16_t cColor)
{
    HANPSTR pRet;

    switch (cColor) {
        case 1: { pRet = sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_5]; } break;
        case 6: { pRet = sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_6]; } break;
        default: { pRet = sg_pJpeg_APP1_ComponentConfigurationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COMPONENT_CONFIGURATION_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_MeteringModeName(uint16_t cMeteringMode)
{
    HANPSTR pRet;

    switch (cMeteringMode) {
        case 1: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_5]; } break;
        case 6: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_6]; } break;
        case 255: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_255]; } break;
        default: { pRet = sg_pJpeg_APP1_MeteringModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_METERING_MODE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_LightSourceName(uint16_t cLightSource)
{
    HANPSTR pRet;

    switch (cLightSource) {
        case 1: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_3]; } break;
        case 9: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_9]; } break;
        case 10: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_10]; } break;
        case 11: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_11]; } break;
        case 12: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_12]; } break;
        case 13: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_13]; } break;
        case 14: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_14]; } break;
        case 15: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_15]; } break;
        case 16: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_16]; } break;
        case 17: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_17]; } break;
        case 18: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_18]; } break;
        case 19: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_19]; } break;
        case 20: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_20]; } break;
        case 21: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_21]; } break;
        case 22: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_22]; } break;
        case 23: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_23]; } break;
        case 24: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_24]; } break;
        case 255: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_255]; } break;
        default: { pRet = sg_pJpeg_APP1_LightSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_LIGHT_SOURCE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FlashFiredName(uint16_t cFlash)
{
    HANPSTR pRet;

    switch (cFlash & 0b01) {
        case 0b00: { pRet = sg_pJpeg_APP1_FlashFiredName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_0]; } break;
        case 0b01: { pRet = sg_pJpeg_APP1_FlashFiredName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FIRED_1]; } break;
        default: {  } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FlashReturnName(uint16_t cFlash)
{
    HANPSTR pRet;

    switch ((cFlash >> 1) & 0b11) {
        case 0b00: { pRet = sg_pJpeg_APP1_FlashReturnName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_00]; } break;
        case 0b01: { pRet = sg_pJpeg_APP1_FlashReturnName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_01]; } break;
        case 0b10: { pRet = sg_pJpeg_APP1_FlashReturnName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_10]; } break;
        case 0b11: { pRet = sg_pJpeg_APP1_FlashReturnName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RETURN_11]; } break;
        default: {  } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FlashModeName(uint16_t cFlash)
{
    HANPSTR pRet;

    switch ((cFlash >> 3) & 0b11) {
        case 0b00: { pRet = sg_pJpeg_APP1_FlashModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_00]; } break;
        case 0b01: { pRet = sg_pJpeg_APP1_FlashModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_01]; } break;
        case 0b10: { pRet = sg_pJpeg_APP1_FlashModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_10]; } break;
        case 0b11: { pRet = sg_pJpeg_APP1_FlashModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_MODE_11]; } break;
        default: {  } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FlashFunctionName(uint16_t cFlash)
{
    HANPSTR pRet;

    switch ((cFlash >> 5) & 0b01) {
        case 0b00: { pRet = sg_pJpeg_APP1_FlashFunctionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_0]; } break;
        case 0b01: { pRet = sg_pJpeg_APP1_FlashFunctionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_FUNCTION_1]; } break;
        default: {  } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FlashRedEyeModeName(uint16_t cFlash)
{
    HANPSTR pRet;

    switch ((cFlash >> 6) & 0b01) {
        case 0b00: { pRet = sg_pJpeg_APP1_FlashRedEyeModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_0]; } break;
        case 0b01: { pRet = sg_pJpeg_APP1_FlashRedEyeModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_RED_EYE_MODE_1]; } break;
        default: {  } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FlashPixVersionName(const uint8_t* pVersion)
{
    HANPSTR pRet;
    
    if (!memcmp(pVersion, "0100", 4)) { pRet = sg_pJpeg_APP1_FlashPixVersionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_0100]; }
    else { pRet = sg_pJpeg_APP1_FlashPixVersionName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FLASH_PIX_VERSION_DEFAULT]; }

    return pRet;
}
HANPSTR GetJpeg_APP1_ColorSpaceName(uint16_t cColorSpace)
{
    HANPSTR pRet;

    switch (cColorSpace) {
        case 1: { pRet = sg_pJpeg_APP1_ColorSpaceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_ColorSpaceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_2]; } break;
        default: { pRet = sg_pJpeg_APP1_ColorSpaceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_COLOR_SPACE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FocalPlaneResolutionUnitName(uint16_t cUnit)
{
    HANPSTR pRet;

    switch (cUnit) {
        case 1: { pRet = sg_pJpeg_APP1_FocalPlaneResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_FocalPlaneResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_FocalPlaneResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_FocalPlaneResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_FocalPlaneResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_5]; } break;
        default: { pRet = sg_pJpeg_APP1_FocalPlaneResolutionUnitName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FOCAL_PLANE_RESOLUTION_UNIT_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_SensingMethodName(uint16_t cSensingMethod)
{
    HANPSTR pRet;

    switch (cSensingMethod) {
        case 1: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_5]; } break;
        case 7: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_7]; } break;
        case 8: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_8]; } break;
        default: { pRet = sg_pJpeg_APP1_SensingMethodName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SENSING_METHOD_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_FileSourceName(uint16_t cSource)
{
    HANPSTR pRet;

    switch (cSource) {
        case 1: { pRet = sg_pJpeg_APP1_FileSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_FileSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_FileSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_3]; } break;
        default: { pRet = sg_pJpeg_APP1_FileSourceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_FILE_SOURCE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_SceneTypeName(uint16_t cSource)
{
    HANPSTR pRet;

    switch (cSource) {
        case 1: { pRet = sg_pJpeg_APP1_SceneTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_1]; } break;
        default: { pRet = sg_pJpeg_APP1_SceneTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_TYPE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_CFAPatternName(uint8_t cCFA)
{
    HANPSTR pRet;

    switch (cCFA) {
        case 0: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_4]; } break;
        case 5: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_5]; } break;
        case 6: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_6]; } break;
        default: { pRet = sg_pJpeg_APP1_CFAPatternName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CFA_PATTERN_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_CustonRenderedName(uint16_t cRender)
{
    HANPSTR pRet;

    switch (cRender) {
        case 0: { pRet = sg_pJpeg_APP1_CustomRenderedName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_CustomRenderedName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_1]; } break;
        default: { pRet = sg_pJpeg_APP1_CustomRenderedName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CUSTOM_REDERED_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_ExposureModeName(uint16_t cMode)
{
    HANPSTR pRet;

    switch (cMode) {
        case 0: { pRet = sg_pJpeg_APP1_ExposureModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_ExposureModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_ExposureModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_2]; } break;
        default: { pRet = sg_pJpeg_APP1_ExposureModeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_EXPOSURE_MODE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_WhiteBalanceName(uint16_t cWhiteBalance)
{
    HANPSTR pRet;

    switch (cWhiteBalance) {
        case 0: { pRet = sg_pJpeg_APP1_WhiteBalanceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_WhiteBalanceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_1]; } break;
        default: { pRet = sg_pJpeg_APP1_WhiteBalanceName[PICTURE_JPEG_APP1_SEGMENT_FIELD_WHITE_BALANCE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_SceneCaptureTypeName(uint16_t cType)
{
    HANPSTR pRet;

    switch (cType) {
        case 0: { pRet = sg_pJpeg_APP1_SceneCaptureTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_SceneCaptureTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_SceneCaptureTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_SceneCaptureTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_3]; } break;
        default: { pRet = sg_pJpeg_APP1_SceneCaptureTypeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SCENE_CAPTURE_TYPE_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_GainControlName(uint16_t cGain)
{
    HANPSTR pRet;

    switch (cGain) {
        case 0: { pRet = sg_pJpeg_APP1_GainControlName[PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_GainControlName[PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_GainControlName[PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_GainControlName[PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_3]; } break;
        case 4: { pRet = sg_pJpeg_APP1_GainControlName[PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_4]; } break;
        default: { pRet = sg_pJpeg_APP1_GainControlName[PICTURE_JPEG_APP1_SEGMENT_FIELD_GAIN_CONTROL_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_ContrastName(uint16_t cContrast)
{
    HANPSTR pRet;

    switch (cContrast) {
        case 0: { pRet = sg_pJpeg_APP1_ContrastName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_ContrastName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_ContrastName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_2]; } break;
        default: { pRet = sg_pJpeg_APP1_ContrastName[PICTURE_JPEG_APP1_SEGMENT_FIELD_CONTRAST_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_SaturationName(uint16_t cSaturation)
{
    HANPSTR pRet;

    switch (cSaturation) {
        case 0: { pRet = sg_pJpeg_APP1_SaturationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_SaturationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_SaturationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_2]; } break;
        default: { pRet = sg_pJpeg_APP1_SaturationName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SATURATION_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_SharpnessName(uint16_t cSharpness)
{
    HANPSTR pRet;

    switch (cSharpness) {
        case 0: { pRet = sg_pJpeg_APP1_SharpnessName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_SharpnessName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_SharpnessName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_2]; } break;
        default: { pRet = sg_pJpeg_APP1_SharpnessName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SHARPNESS_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP1_SubjectDistanceRangeName(uint16_t cDis)
{
    HANPSTR pRet;

    switch (cDis) {
        case 0: { pRet = sg_pJpeg_APP1_SubjectDistanceRangeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_0]; } break;
        case 1: { pRet = sg_pJpeg_APP1_SubjectDistanceRangeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_1]; } break;
        case 2: { pRet = sg_pJpeg_APP1_SubjectDistanceRangeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_2]; } break;
        case 3: { pRet = sg_pJpeg_APP1_SubjectDistanceRangeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_3]; } break;
        default: { pRet = sg_pJpeg_APP1_SubjectDistanceRangeName[PICTURE_JPEG_APP1_SEGMENT_FIELD_SUBJECT_DISTANCE_RANGE_DEFAULT]; } break;
    }

    return pRet;
}
#endif

#if 1 /******************** APP2 ********************/
typedef enum {
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT2,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT3,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT4,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_CNT,
} PICTUREJPEGAPP2SEGMENTFIELDMPIMAGEFLAGS;
typedef enum {
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_0,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_DEFAULT,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_CNT,
} PICTUREJPEGAPP2SEGMENTFIELDMPIMAGEFORMAT;
typedef enum {
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_0,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10001,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10002,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10003,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10004,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10005,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20001,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20002,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20003,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_30000,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_40000,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_50000,
    PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_CNT,
} PICTUREJPEGAPP2SEGMENTFIELDMPIMAGETYPE;

static const HANPSTR sg_pJpeg_APP2_Name = TEXT("APP2");
static const HANPSTR sg_pJpegSegmentFieldName_APP2[PICTURE_JPEG_APP2_SEGMENT_FIELD_CNT] = {
    /* MPF */
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_VERSION] = TEXT("MPF版本"),                                                    // B000
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_NUMBER_OF_IMAGES] = TEXT("图像数量"),                                          // B001
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_MP_IMAGE_FLAGS] = TEXT("属性"),                                                // B002
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_MP_IMAGE_FORMAT] = TEXT("格式"),                                               // B002
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_MP_IMAGE_TYPE] = TEXT("类型"),                                                 // B002
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_MP_IMAGE_LENGTH] = TEXT("大小"),                                               // B002
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_MP_IMAGE_START] = TEXT("位置"),                                                // B002
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_MP_IMAGE_DEPENDENT_IMAGE1_ENTRY_NUMBER] = TEXT("从属图像1条目编号"),            // B002
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MPF_MP_IMAGE_DEPENDENT_IMAGE2_ENTRY_NUMBER] = TEXT("从属图像2条目编号"),            // B002
};
static const HANPSTR sg_pJpeg_APP2_MPImageFlagsName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_CNT] = {
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT2] = TEXT("主图像"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT3] = TEXT("相关图像的子图像"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT4] = TEXT("相关图像的父图像"),
};
static const HANPSTR sg_pJpeg_APP2_MPImageFormatName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_CNT] = {
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_0] = TEXT("JPEG"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_DEFAULT] = TEXT("其它"),
};
static const HANPSTR sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_CNT] = {
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_0] = TEXT("未定义"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10001] = TEXT("大缩略图（相当于VGA）"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10002] = TEXT("大缩略图（相当于全高清）"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10003] = TEXT("大缩略图（相当于4K）"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10004] = TEXT("大缩略图（相当于8K）"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10005] = TEXT("大缩略图（相当于16K）"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20001] = TEXT("多帧全景"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20002] = TEXT("多帧视差"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20003] = TEXT("多角度"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_30000] = TEXT("基线MP主图像"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_40000] = TEXT("原始保存图像"),
    [PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_50000] = TEXT("增益映射图像"),
};

HANPSTR GetJpeg_APP2_Name(void)
{
    return sg_pJpeg_APP2_Name;
}
HANPSTR GetJpeg_APP2_FieldName(PICTUREJPEGSEGMENTFIELD_APP2 eName)
{
    return sg_pJpegSegmentFieldName_APP2[eName];
}
void GetJpeg_APP2_MPImageFlagsName(uint32_t cMask, HANPSTR pText)
{
    const HANPCSTR pPrint[2] = { [0] = TEXT(""), [1] = TEXT("，"), };
    uint32_t cFlag = (cMask >> 27) & 0x1F;
    HANSIZE nId = 0;

    HAN_strcpy(pText, TEXT(""));
    if (0 != (cFlag & 0b00100))
    {
        HAN_strcat(pText, pPrint[nId]);
        HAN_strcat(pText, sg_pJpeg_APP2_MPImageFlagsName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT2]);
        nId = 1;
    }
    if (0 != (cFlag & 0b01000))
    {
        HAN_strcat(pText, pPrint[nId]);
        HAN_strcat(pText, sg_pJpeg_APP2_MPImageFlagsName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT3]);
        nId = 1;
    }
    if (0 != (cFlag & 0b10000))
    {
        HAN_strcat(pText, pPrint[nId]);
        HAN_strcat(pText, sg_pJpeg_APP2_MPImageFlagsName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FLAGS_BIT4]);
        nId = 1;
    }
}
HANPSTR GetJpeg_APP2_MPImageFormatName(uint32_t cMask)
{
    HANPSTR pRet;

    switch ((cMask >> 24) & 0x07) {
        case 0: { pRet = sg_pJpeg_APP2_MPImageFormatName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_0]; } break;
        default: { pRet = sg_pJpeg_APP2_MPImageFormatName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_FORMAT_DEFAULT]; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_APP2_MPImageTypeName(uint32_t cMask)
{
    HANPSTR pRet;

    switch (cMask & 0xFFFFFF) {
        case 0x10001: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10001]; } break;
        case 0x10002: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10002]; } break;
        case 0x10003: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10003]; } break;
        case 0x10004: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10004]; } break;
        case 0x10005: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_10005]; } break;
        case 0x20001: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20001]; } break;
        case 0x20002: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20002]; } break;
        case 0x20003: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_20003]; } break;
        case 0x30000: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_30000]; } break;
        case 0x40000: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_40000]; } break;
        case 0x50000: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_50000]; } break;
        default: { pRet = sg_pJpeg_APP2_MPImageTypeName[PICTURE_JPEG_APP2_SEGMENT_FIELD_MP_IMAGE_TYPE_0]; } break;
    }

    return pRet;
}
#endif

#if 1 /******************** COM ********************/
static const HANPSTR sg_pJpeg_COM_Name = TEXT("注释");
static const HANPSTR sg_pJpegSegmentFieldName_COM[PICTURE_JPEG_COM_SEGMENT_FIELD_CNT] = {
    [PICTURE_JPEG_COM_SEGMENT_FIELD_COMMENT] = TEXT("注释"),
};

HANPSTR GetJpeg_COM_Name(void)
{
    return sg_pJpeg_COM_Name;
}
HANPSTR GetJpeg_COM_FieldName(PICTUREJPEGSEGMENTFIELD_COM eName)
{
    return sg_pJpegSegmentFieldName_COM[eName];
}
#endif

#if 1 /******************** DQT ********************/
static const HANPSTR sg_pJpeg_DQT_Name = TEXT("量化表");

HANPSTR GetJpeg_DQT_Name(void)
{
    return sg_pJpeg_DQT_Name;
}
#endif

#if 1 /******************** DHT ********************/
static const HANPSTR sg_pJpeg_DHT_Name = TEXT("Huffman表");

HANPSTR GetJpeg_DHT_Name(void)
{
    return sg_pJpeg_DHT_Name;
}
#endif

#if 1 /******************** SOFn ********************/
typedef enum {
    PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_1,
    PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_2,
    PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_3,
    PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_4,
    PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_5,
    PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_DEFAULT,
    PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_CNT,
} PICTUREJPEGSOFnSEGMENTFIELDCOMPONENT;

static const HANPSTR sg_pJpeg_SOF0_Name = TEXT("标准JPEG基本信息");
static const HANPSTR sg_pJpeg_SOF2_Name = TEXT("渐近式JPEG基本信息");
static const HANPSTR sg_pJpegSegmentFieldName_SOFn[PICTURE_JPEG_SOFn_SEGMENT_FIELD_CNT] = {
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_BIT_DEPTH] = TEXT("位深"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_HEIGHT] = TEXT("图像高度"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_WIDTH] = TEXT("图像宽度"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_NUM] = TEXT("分量数"),
};
static const HANPSTR sg_pJpeg_SOFn_ComponentName[PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_CNT] = {
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_1] = TEXT("Y"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_2] = TEXT("Cb"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_3] = TEXT("Cr"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_4] = TEXT("I"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_5] = TEXT("Q"),
    [PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_DEFAULT] = TEXT("未知分量"),
};
static const HANPSTR sg_pJpeg_SOFn_ComponentSamplingFactorName = TEXT("采样因子");
static const HANPSTR sg_pJpeg_SOFn_ComponentQuantitativeTableIdName = TEXT("量化表ID");

HANPSTR GetJpeg_SOFn_Name(uint16_t cMarker)
{
    HANPSTR pRet;

    switch (cMarker) {
        case 0xFFC0: { pRet = sg_pJpeg_SOF0_Name; } break;
        case 0xFFC2: { pRet = sg_pJpeg_SOF2_Name; } break;
    }

    return pRet;
}
HANPSTR GetJpeg_SOFn_FieldName(PICTUREJPEGSEGMENTFIELD_SOFn eName)
{
    return sg_pJpegSegmentFieldName_SOFn[eName];
}
void GetJpeg_SOFn_ComponentName(uint32_t cComponent, HANPSTR pText)
{
    HAN_strcpy(pText, TEXT("分量"));
    switch (cComponent) {
        case 1: { HAN_strcat(pText, sg_pJpeg_SOFn_ComponentName[PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_1]); } break;
        case 2: { HAN_strcat(pText, sg_pJpeg_SOFn_ComponentName[PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_2]); } break;
        case 3: { HAN_strcat(pText, sg_pJpeg_SOFn_ComponentName[PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_3]); } break;
        case 4: { HAN_strcat(pText, sg_pJpeg_SOFn_ComponentName[PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_4]); } break;
        case 5: { HAN_strcat(pText, sg_pJpeg_SOFn_ComponentName[PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_5]); } break;
        default: { HAN_strcpy(pText, sg_pJpeg_SOFn_ComponentName[PICTURE_JPEG_SOFn_SEGMENT_FIELD_COMPONENT_DEFAULT]); } break;
    }
}
HANPSTR GetJpeg_SOFn_ComponentSamplingFactorName(void) { return sg_pJpeg_SOFn_ComponentSamplingFactorName; }
HANPSTR GetJpeg_SOFn_ComponentQuantitativeTableIdName(void) { return sg_pJpeg_SOFn_ComponentQuantitativeTableIdName; }
#endif

#if 1 /******************** DRI ********************/
static const HANPSTR sg_pJpeg_DRI_Name = TEXT("重启间隔");
static const HANPSTR sg_pJpegSegmentFieldName_DRI[PICTURE_JPEG_DRI_SEGMENT_FIELD_CNT] = {
    [PICTURE_JPEG_DRI_SEGMENT_FIELD_RESTART_INTERVAL] = TEXT("重启间隔"),
};

HANPSTR GetJpeg_DRI_Name(void)
{
    return sg_pJpeg_DRI_Name;
}
HANPSTR GetJpeg_DRI_FieldName(PICTUREJPEGSEGMENTFIELD_DRI eName)
{
    return sg_pJpegSegmentFieldName_DRI[eName];
}
#endif

#if 1 /******************** SOS ********************/
static const HANPSTR sg_pJpeg_SOS_Name = TEXT("图像压缩数据");
static const HANPSTR sg_pJpegSegmentFieldName_SOS[PICTURE_JPEG_SOS_SEGMENT_FIELD_CNT] = {
    [PICTURE_JPEG_SOS_SEGMENT_FIELD_COMPONENT_NUM] = TEXT("分量数"),
    [PICTURE_JPEG_SOS_SEGMENT_FIELD_COMPONENT_Y] = TEXT("亮度分量"),
    [PICTURE_JPEG_SOS_SEGMENT_FIELD_COMPONENT_Cb] = TEXT("Cb分量"),
    [PICTURE_JPEG_SOS_SEGMENT_FIELD_COMPONENT_Cr] = TEXT("Cr分量"),
    [PICTURE_JPEG_SOS_SEGMENT_FIELD_SPECTRAL_START] = TEXT("频谱开始位置"),
    [PICTURE_JPEG_SOS_SEGMENT_FIELD_SPECTRAL_END] = TEXT("频谱结束位置"),
    [PICTURE_JPEG_SOS_SEGMENT_FIELD_PROGRESSIVE] = TEXT("渐近位"),
};

HANPSTR GetJpeg_SOS_Name(void)
{
    return sg_pJpeg_SOS_Name;
}
HANPSTR GetJpeg_SOS_FieldName(PICTUREJPEGSEGMENTFIELD_SOS eName)
{
    return sg_pJpegSegmentFieldName_SOS[eName];
}
#endif

#if 1 /******************** RSTn ********************/
static const HANPSTR sg_pJpeg_RSTn_Name = TEXT("DC重启标记");

HANPSTR GetJpeg_RSTn_Name(void)
{
    return sg_pJpeg_RSTn_Name;
}
#endif

#if 1 /******************** EOI ********************/
static const HANPSTR sg_pJpeg_EOI_Name = TEXT("文件尾");

HANPSTR GetJpeg_EOI_Name(void)
{
    return sg_pJpeg_EOI_Name;
}
#endif
