#ifndef HAN_PICTURE_JPEG_MATH_H
#define HAN_PICTURE_JPEG_MATH_H

#ifdef __cplusplus
extern "C" {
#endif

#include "HAN_PictureJpegDef.h"

typedef int32_t             PICTUREJPEGNUMBER;
typedef HANDOUBLE           PICTUREJPEGFLOATROW[8];
typedef HANDOUBLE           PICTUREJPEGFLOATMATRIX[8][8];
typedef PICTUREJPEGNUMBER   PICTUREJPEGDCTROW[8];
typedef PICTUREJPEGNUMBER   PICTUREJPEGDCTMATRIX1D[64];
typedef PICTUREJPEGNUMBER   PICTUREJPEGDCTMATRIX2D[8][8];

void PictureJpegDCT(PICTUREJPEGDCTMATRIX2D* pDest, const PICTUREJPEGDCTMATRIX2D* pSrc, HANSIZE nLen);

void PictureJpegIDCT(PICTUREJPEGDCTMATRIX2D* pDest, const PICTUREJPEGDCTMATRIX2D* pSrc, HANSIZE nLen);
void PictureJpegFastIDCT(PICTUREJPEGDCTMATRIX2D* pDest, const PICTUREJPEGDCTMATRIX2D* pSrc, HANSIZE nLen);

#ifdef __cplusplus
}
#endif

#endif
