#include "HAN_PictureJpegMakerNoteSonyTag.h"

typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_3,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_4,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_5,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_6,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_7,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_8,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_9,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_CNT,
} PICTUREJPEGMAKERNOTESONYTAGAFPOINTSELECTED;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_3,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_CNT,
} PICTUREJPEGMAKERNOTESONYTAGFOCUSMODE;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_3,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_4,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_5,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_6,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_7,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_CNT,
} PICTUREJPEGMAKERNOTESONYTAGAFPOINT;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_4,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_16,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_24,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_64,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_CNT,
} PICTUREJPEGMAKERNOTESONYTAGFOCUSSTATUS;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_3,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_4,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_5,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_6,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_7,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_8,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_9,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_4294967295,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_CNT,
} PICTUREJPEGMAKERNOTESONYTAGQUALITY;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_4,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_5,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x48,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x50,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x60,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x88,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x90,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_xA0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_CNT,
} PICTUREJPEGMAKERNOTESONYTAGTELECONVERTER;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_00,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_01,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_10,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_20,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_30,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_40,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_50,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_60,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_70,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_80,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_CNT,
} PICTUREJPEGMAKERNOTESONYTAGWHITEBALANCE;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_64,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_CNT,
} PICTUREJPEGMAKERNOTESONYTAGIMAGESTABILIZATION0116;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_248,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_249,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_250,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_251,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_252,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_253,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_254,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_255,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_CNT,
} PICTUREJPEGMAKERNOTESONYTAGMODEDIALPOSITION;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_244,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_245,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_252,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_254,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_CNT,
} PICTUREJPEGMAKERNOTESONYTAGMEMCARDCFG;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_3,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_CNT,
} PICTUREJPEGMAKERNOTESONYTAGCAMERAORIENTATION;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_10001,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFF0000,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFF0001,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFFFFFF,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_CNT,
} PICTUREJPEGMAKERNOTESONYTAGLONGEXPOSURENOISEREDUCTION;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_3,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_256,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_65535,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_CNT,
} PICTUREJPEGMAKERNOTESONYTAGHIGHISONOISEREDUCTION;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_10,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_11,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_12,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_13,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_14,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_15,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_16,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_17,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_18,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_19,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_1A,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_CNT,
} PICTUREJPEGMAKERNOTESONYTAGHDRVALUE0;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_3,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_CNT,
} PICTUREJPEGMAKERNOTESONYTAGHDRVALUE1;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_255,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_CNT,
} PICTUREJPEGMAKERNOTESONYTAGMULTIFRAMENOISEREDUCTION;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_OTHER,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_CNT,
} PICTUREJPEGMAKERNOTESONYTAGFACEDETECTION;
typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_0,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_33,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_57,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_77,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_93,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_98,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_115,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_168,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_241,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_DEFAULT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_CNT,
} PICTUREJPEGMAKERNOTESONYTAGFACEDETECTED;

static const HANPCSTR sg_pJpegMakerNoteSonyTagName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LENS_SPEC_0010] = TEXT("镜头规格"),                               // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCAL_LENGTH] = TEXT("焦距"),                                     // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCAL_LENGTH_TELE_ZOOM] = TEXT("35mm焦距"),                       // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED] = TEXT("自动对焦点选择"),                      // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE] = TEXT("对焦模式"),                                   // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT] = TEXT("自动对焦点"),                                   // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS] = TEXT("焦点状态"),                                 // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_ACTIVE_SENSOR] = TEXT("AFStatusActiveSensor"),          // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_UPPER_LEFT] = TEXT("AFStatusUpper-left"),               // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LEFT] = TEXT("AFStatusLeft"),                           // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LOWER_LEFT] = TEXT("AFStatusLower-left"),               // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_FAR_LEFT] = TEXT("AFStatusFarLeft"),                    // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_TOP_HORIZONTAL] = TEXT("AFStatusTopHorizontal"),        // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_NEAR_RIGHT] = TEXT("AFStatusNearRight"),                // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_CENTER_HORIZONTAL] = TEXT("AFStatusCenterHorizontal"),  // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_NEAR_LEFT] = TEXT("AFStatusNearLeft"),                  // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_BOTTOM_HORIZONTAL] = TEXT("AFStatusBottomHorizontal"),  // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_TOP_VERTICAL] = TEXT("AFStatusTopVertical"),            // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_CENTER_VERTICAL] = TEXT("AFStatusCenterVertical"),      // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_BOTTOM_VERTICAL] = TEXT("AFStatusBottomVertical"),      // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_FAR_RIGHT] = TEXT("AFStatusFarRight"),                  // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_UPPER_RIGHT] = TEXT("AFStatusUpper-right"),             // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_RIGHT] = TEXT("AFStatusRight"),                         // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LOWER_RIGHT] = TEXT("AFStatusLower-right"),             // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_UPPER_MIDDLE] = TEXT("AFStatusUpper-middle"),           // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LOWER_MIDDLE] = TEXT("AFStatusLower-middle"),           // 0010
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY] = TEXT("质量"),                                          // 0102
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FLASH_EXPOSURE_COMP] = TEXT("闪光补偿"),                          // 0104
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER] = TEXT("增距镜"),                                  // 0105
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_FINE_TUNE] = TEXT("白平衡微调"),                    // 0112
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE] = TEXT("白平衡"),                                  // 0115
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_UNKNOWN] = TEXT("电池未知信息"),                          // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_TEMPERATURE] = TEXT("电池温度"),                          // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_LEVEL] = TEXT("电池等级"),                                // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_VOLTAGE1] = TEXT("电池电压1"),                            // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_VOLTAGE2] = TEXT("电池电压2"),                            // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116] = TEXT("图像稳定器"),                   // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_STATE] = TEXT("图像状态"),                                // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_EXPOSURE_PROGRAM] = TEXT("曝光方式"),                             // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION] = TEXT("模式拨盘位置"),                       // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG] = TEXT("内存卡配置"),                               // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION] = TEXT("相机方向"),                           // 0116
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_RATING] = TEXT("Rating"),                                         // 2002
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CONTRAST] = TEXT("对比度"),                                       // 2004
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_SATURATION] = TEXT("饱和度"),                                     // 2005
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_SHARPNESS] = TEXT("锐度"),                                        // 2006
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BRIGHTNESS] = TEXT("亮度"),                                       // 2007
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION] = TEXT("长曝光降噪"),              // 2008
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION] = TEXT("高ISO降噪"),                    // 2009
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR] = TEXT("HDR"),                                               // 200A
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION] = TEXT("多帧降噪"),                  // 200B
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_COLOR_TEMPERATURE] = TEXT("色温"),                                // B021
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_COLOR_COMPENSATION_FILTER] = TEXT("彩色补偿滤镜"),                // B022
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_SCENE_MODE] = TEXT("场景模式"),                                   // B023
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_ZONE_MATCHING] = TEXT("区域匹配"),                                // B024
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_DYNAMIC_RANGE_OPTIMIZER] = TEXT("动态范围优化"),                  // B025
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_B026] = TEXT("图像稳定器"),                   // B026
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LENS_TYPE] = TEXT("镜头类型"),                                    // B027
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_COLOR_MODE] = TEXT("色彩模式"),                                   // B029
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LENS_SPEC_B02A] = TEXT("镜头规格"),                               // B02A
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION] = TEXT("人脸检测"),                               // 900B
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED] = TEXT("人脸数量"),                                // 900B
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_0] = TEXT("自动"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_1] = TEXT("中心"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_2] = TEXT("顶部"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_3] = TEXT("右上"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_4] = TEXT("右侧"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_5] = TEXT("右下"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_6] = TEXT("底部"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_7] = TEXT("左下"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_8] = TEXT("左侧"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_9] = TEXT("左上"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_DEFAULT] = TEXT("其它"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagFocusModeName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_0] = TEXT("手动对焦"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_1] = TEXT("单次自动对焦"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_2] = TEXT("连续自动对焦"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_3] = TEXT("人工智能自动对焦"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_DEFAULT] = TEXT("其它"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_0] = TEXT("右上"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_1] = TEXT("右下"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_2] = TEXT("底部"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_3] = TEXT("水平居中"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_4] = TEXT("垂直居中"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_5] = TEXT("顶部"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_6] = TEXT("左上"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_7] = TEXT("左下"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_DEFAULT] = TEXT("其它"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagFocusStatusName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_0] = TEXT("手动对焦-未确认(0)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_4] = TEXT("手动对焦-未确认(4)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_16] = TEXT("连续自动对焦-确认完成"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_24] = TEXT("连续自动对焦-未确认"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_64] = TEXT("单次自动对焦-确认完成"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_DEFAULT] = TEXT("其它"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_0] = TEXT("RAW"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_1] = TEXT("Super Fine"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_2] = TEXT("Fine"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_3] = TEXT("Standard"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_4] = TEXT("Economy"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_5] = TEXT("Extra Fine"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_6] = TEXT("RAW + JPEG/HEIF"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_7] = TEXT("Compressed RAW"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_8] = TEXT("Compressed RAW + JPEG"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_9] = TEXT("Light"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_4294967295] = TEXT("N/A"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_0] = TEXT("未使用"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_4] = TEXT("Minolta/Sony AF 1.4x APO (D) (0x04)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_5] = TEXT("Minolta/Sony AF 2x APO (D) (0x05)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x48] = TEXT("Minolta/Sony AF 2x APO (D)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x50] = TEXT("Minolta AF 2x APO II"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x60] = TEXT("Minolta AF 2x APO"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x88] = TEXT("Minolta/Sony AF 1.4x APO (D)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x90] = TEXT("Minolta AF 1.4x APO II"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_xA0] = TEXT("Minolta AF 1.4x APO"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_00] = TEXT("自动"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_01] = TEXT("色温/滤色器"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_10] = TEXT("日光"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_20] = TEXT("多云"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_30] = TEXT("阴天"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_40] = TEXT("钨丝灯"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_50] = TEXT("闪光灯"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_60] = TEXT("荧光灯"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_70] = TEXT("自定义"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_80] = TEXT("水下"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_DEFAULT] = TEXT("其他"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagImageStabilizationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_0] = TEXT("关闭"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_64] = TEXT("启用"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_DEFAULT] = TEXT("其他"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_248] = TEXT("No Flash"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_249] = TEXT("Aperture-priority AE"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_250] = TEXT("SCN"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_251] = TEXT("Shutter speed priority AE"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_252] = TEXT("Auto"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_253] = TEXT("Program AE"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_254] = TEXT("Panorama"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_255] = TEXT("Manual"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_DEFAULT] = TEXT("其他"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagMemoryCardConfigurationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_244] = TEXT("MemoryStick in use, SD card present"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_245] = TEXT("MemoryStick in use, SD slot empty"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_252] = TEXT("SD card in use, MemoryStick present"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_254] = TEXT("SD card in use, MemoryStick slot empty"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagCameraOrientationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_0] = TEXT("水平"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_1] = TEXT("顺时针90°"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_2] = TEXT("顺时针270°"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_3] = TEXT("旋转180°"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_0] = TEXT("关闭"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_1] = TEXT("开启（未使用）"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_10001] = TEXT("开启（拍摄暗帧并处理）"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFF0000] = TEXT("关闭（65535）"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFF0001] = TEXT("开启（65535"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFFFFFF] = TEXT("N/A"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_0] = TEXT("关闭"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_1] = TEXT("低"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_2] = TEXT("标准"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_3] = TEXT("高"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_256] = TEXT("自动"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_65535] = TEXT("N/A"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_0] = TEXT("Off"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_1] = TEXT("Auto"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_10] = TEXT("1.0 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_11] = TEXT("1.5 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_12] = TEXT("2.0 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_13] = TEXT("2.5 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_14] = TEXT("3.0 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_15] = TEXT("3.5 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_16] = TEXT("4.0 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_17] = TEXT("4.5 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_18] = TEXT("5.0 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_19] = TEXT("5.5 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_1A] = TEXT("6.0 EV"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagHDRValue1Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_0] = TEXT("Uncorrected image"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_1] = TEXT("HDR image (good)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_2] = TEXT("HDR image (fail 1)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_3] = TEXT("HDR image (fail 2)"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagMultiFrameNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_0] = TEXT("关闭"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_1] = TEXT("开启"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_255] = TEXT("N/A"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_DEFAULT] = TEXT("未知"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagFaceDetectionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_0] = TEXT("关闭"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_OTHER] = TEXT("启用"),
};
static const HANPCSTR sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_CNT] = {
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_0] = TEXT("0"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_33] = TEXT("5"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_57] = TEXT("2"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_77] = TEXT("4"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_93] = TEXT("3"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_98] = TEXT("1"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_115] = TEXT("8"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_168] = TEXT("6"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_241] = TEXT("7"),
    [PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_DEFAULT] = TEXT("未知"),
};

HANPCSTR GetJpegMakerNoteSonyTagName(PICTUREJPEGMAKERNOTESONYTAG eName)
{
    return sg_pJpegMakerNoteSonyTagName[eName];
}
HANPCSTR GetJpegMakerNoteSonyTagAFPointSelectedName(uint8_t cSelect)
{
    HANPCSTR pRet;

    switch (cSelect) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_1]; } break;
        case 2: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_2]; } break;
        case 3: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_3]; } break;
        case 4: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_4]; } break;
        case 5: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_5]; } break;
        case 6: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_6]; } break;
        case 7: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_7]; } break;
        case 8: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_8]; } break;
        case 9: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_9]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagAFPointSelectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagFocusModeName(uint8_t cMode)
{
    HANPCSTR pRet;

    switch (cMode) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagFocusModeName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagFocusModeName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_1]; } break;
        case 2: { pRet = sg_pJpegMakerNoteSonyTagFocusModeName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_2]; } break;
        case 3: { pRet = sg_pJpegMakerNoteSonyTagFocusModeName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_3]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagFocusModeName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagAFPointName(uint8_t cPoint)
{
    HANPCSTR pRet;

    switch (cPoint) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_1]; } break;
        case 2: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_2]; } break;
        case 3: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_3]; } break;
        case 4: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_4]; } break;
        case 5: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_5]; } break;
        case 6: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_6]; } break;
        case 7: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_7]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagAFPointName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagFocusStatusName(uint8_t cPoint)
{
    HANPCSTR pRet;

    switch (cPoint) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagFocusStatusName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_0]; } break;
        case 4: { pRet = sg_pJpegMakerNoteSonyTagFocusStatusName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_4]; } break;
        case 16: { pRet = sg_pJpegMakerNoteSonyTagFocusStatusName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_16]; } break;
        case 24: { pRet = sg_pJpegMakerNoteSonyTagFocusStatusName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_24]; } break;
        case 64: { pRet = sg_pJpegMakerNoteSonyTagFocusStatusName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_64]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagFocusStatusName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagQualityName(uint32_t cQuality)
{
    HANPCSTR pRet;

    switch (cQuality) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_1]; } break;
        case 2: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_2]; } break;
        case 3: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_3]; } break;
        case 4: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_4]; } break;
        case 5: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_5]; } break;
        case 6: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_6]; } break;
        case 7: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_7]; } break;
        case 8: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_8]; } break;
        case 9: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_9]; } break;
        case 4294967295: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_4294967295]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagQualityName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagTeleconverterName(uint32_t cTeleconverter)
{
    HANPCSTR pRet;

    switch (cTeleconverter) {
        case 0x00: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_0]; } break;
        case 0x04: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_4]; } break;
        case 0x05: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_5]; } break;
        case 0x48: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x48]; } break;
        case 0x50: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x50]; } break;
        case 0x60: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x60]; } break;
        case 0x88: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x88]; } break;
        case 0x90: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_x90]; } break;
        case 0xA0: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_xA0]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagTeleconverterName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagWhiteBalanceName(uint32_t cWhiteBalance)
{
    HANPCSTR pRet;

    switch (cWhiteBalance) {
        case 0x00: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_00]; } break;
        case 0x01: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_01]; } break;
        case 0x10: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_10]; } break;
        case 0x20: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_20]; } break;
        case 0x30: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_30]; } break;
        case 0x40: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_40]; } break;
        case 0x50: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_50]; } break;
        case 0x60: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_60]; } break;
        case 0x70: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_70]; } break;
        case 0x80: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_80]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagWhiteBalanceName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagImageStabilizationName(uint32_t cStab)
{
    HANPCSTR pRet;

    switch (cStab) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagImageStabilizationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_0]; } break;
        case 64: { pRet = sg_pJpegMakerNoteSonyTagImageStabilizationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_64]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagImageStabilizationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagModeDialPositionName(uint32_t cPosition)
{
    HANPCSTR pRet;

    switch (cPosition) {
        case 248: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_248]; } break;
        case 249: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_249]; } break;
        case 250: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_250]; } break;
        case 251: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_251]; } break;
        case 252: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_252]; } break;
        case 253: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_253]; } break;
        case 254: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_254]; } break;
        case 255: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_255]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagModeDialPositionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagMemoryCardConfigurationName(uint32_t cCfg)
{
    HANPCSTR pRet;

    switch (cCfg) {
        case 244: { pRet = sg_pJpegMakerNoteSonyTagMemoryCardConfigurationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_244]; } break;
        case 245: { pRet = sg_pJpegMakerNoteSonyTagMemoryCardConfigurationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_245]; } break;
        case 252: { pRet = sg_pJpegMakerNoteSonyTagMemoryCardConfigurationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_252]; } break;
        case 254: { pRet = sg_pJpegMakerNoteSonyTagMemoryCardConfigurationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_254]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagMemoryCardConfigurationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagCameraOrientationName(uint32_t cOrientation)
{
    HANPCSTR pRet;

    switch (cOrientation) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagCameraOrientationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagCameraOrientationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_1]; } break;
        case 2: { pRet = sg_pJpegMakerNoteSonyTagCameraOrientationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_2]; } break;
        case 3: { pRet = sg_pJpegMakerNoteSonyTagCameraOrientationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_3]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagCameraOrientationName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagLongExposureNoiseReductionName(uint32_t cLongExposureNoiseReduction)
{
    HANPCSTR pRet;

    switch (cLongExposureNoiseReduction) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_1]; } break;
        case 0x10001: { pRet = sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_10001]; } break;
        case 0xFFFF0000: { pRet = sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFF0000]; } break;
        case 0xFFFF0001: { pRet = sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFF0001]; } break;
        case 0xFFFFFFFF: { pRet = sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_FFFFFFFF]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagLongExposureNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagHighISONoiseReductionName(uint16_t cHighISONoiseReduction)
{
    HANPCSTR pRet;

    switch (cHighISONoiseReduction) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_1]; } break;
        case 2: { pRet = sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_2]; } break;
        case 3: { pRet = sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_3]; } break;
        case 256: { pRet = sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_256]; } break;
        case 65535: { pRet = sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_65535]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagHighISONoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagHDRValue0Name(uint16_t cHDR0)
{
    HANPCSTR pRet;

    switch (cHDR0) {
        case 0x0: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_0]; } break;
        case 0x1: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_1]; } break;
        case 0x10: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_10]; } break;
        case 0x11: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_11]; } break;
        case 0x12: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_12]; } break;
        case 0x13: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_13]; } break;
        case 0x14: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_14]; } break;
        case 0x15: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_15]; } break;
        case 0x16: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_16]; } break;
        case 0x17: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_17]; } break;
        case 0x18: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_18]; } break;
        case 0x19: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_19]; } break;
        case 0x1A: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_1A]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagHDRValue0Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE0_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagHDRValue1Name(uint16_t cHDR1)
{
    HANPCSTR pRet;

    switch (cHDR1) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagHDRValue1Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagHDRValue1Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_1]; } break;
        case 2: { pRet = sg_pJpegMakerNoteSonyTagHDRValue1Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_2]; } break;
        case 3: { pRet = sg_pJpegMakerNoteSonyTagHDRValue1Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_3]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagHDRValue1Name[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR_VALUE1_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagMultiFrameNoiseReductionName(uint32_t cMultiFrameNoiseReduction)
{
    HANPCSTR pRet;

    switch (cMultiFrameNoiseReduction) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagMultiFrameNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_0]; } break;
        case 1: { pRet = sg_pJpegMakerNoteSonyTagMultiFrameNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_1]; } break;
        case 255: { pRet = sg_pJpegMakerNoteSonyTagMultiFrameNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_255]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagMultiFrameNoiseReductionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION_DEFAULT]; } break;
    }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagFaceDetectionName(uint8_t cFaceDetection)
{
    HANPCSTR pRet;

    if (0 == cFaceDetection) { pRet = sg_pJpegMakerNoteSonyTagFaceDetectionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_0]; }
    else { pRet = sg_pJpegMakerNoteSonyTagFaceDetectionName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION_OTHER]; }

    return pRet;
}
HANPCSTR GetJpegMakerNoteSonyTagFaceDetectedName(uint8_t cFaceDetected)
{
    HANPCSTR pRet;

    switch (cFaceDetected) {
        case 0: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_0]; } break;
        case 33: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_33]; } break;
        case 57: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_57]; } break;
        case 77: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_77]; } break;
        case 93: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_93]; } break;
        case 98: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_98]; } break;
        case 115: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_115]; } break;
        case 168: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_168]; } break;
        case 241: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_241]; } break;

        default: { pRet = sg_pJpegMakerNoteSonyTagFaceDetectedName[PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED_DEFAULT]; } break;
    }

    return pRet;
}
