#include "HAN_PictureJpegMakerNoteSonyLensType.h"

void UpdateSegmentInfoWindow_APP1_ExifReadSonyGetLensTypeName(HANPSTR pText, size_t nTextSize, uint32_t cType)
{
    switch (cType) {
        case 0: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-85mm F3.5-4.5 New")); } break;
        case 1: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F2.8 HS-APO G")); } break;
        case 2: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-70mm F2.8 G")); } break;
        case 3: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-80mm F4-5.6")); } break;
        case 4: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 85mm F1.4G")); } break;
        case 5: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-70mm F3.5-4.5 [II]")); } break;
        case 6: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24-85mm F3.5-4.5 [New]")); } break;
        case 7: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6 APO [New] or 100-400mm or Sigma Lens")); } break;
        // case 7: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-400mm F4.5-6.7 APO")); } break;
        // case 7: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 100-300mm F4 EX DG IF")); } break;
        case 8: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 70-210mm F4.5-5.6 [II]")); } break;
        case 9: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F3.5 Macro")); } break;
        case 10: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-105mm F3.5-4.5 [New]")); } break;
        case 11: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 300mm F4 HS-APO G")); } break;
        case 12: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100mm F2.8 Soft Focus")); } break;
        case 13: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 75-300mm F4.5-5.6 (New or II)")); } break;
        case 14: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-400mm F4.5-6.7 APO")); } break;
        case 15: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 400mm F4.5 HS-APO G")); } break;
        case 16: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 17-35mm F3.5 G")); } break;
        case 17: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 20-35mm F3.5-4.5")); } break;
        case 18: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-80mm F3.5-5.6 II")); } break;
        case 19: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35mm F1.4 G")); } break;
        case 20: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony 135mm F2.8 [T4.5] STF")); } break;
        case 22: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-80mm F4-5.6 II")); } break;
        case 23: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F4 Macro APO G")); } break;
        case 24: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 24-105mm F3.5-4.5 (D) or Sigma or Tamron Lens")); } break;
        // case 24: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 18-50mm F2.8")); } break;
        // case 24: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 17-70mm F2.8-4.5 DC Macro")); } break;
        // case 24: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 20-40mm F2.8 EX DG Aspherical IF")); } break;
        // case 24: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 18-200mm F3.5-6.3 DC")); } break;
        // case 24: { HAN_snprintf(pText, nTextSize, TEXT("Sigma DC 18-125mm F4-5,6 D")); } break;
        // case 24: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 28-75mm F2.8 XR Di LD Aspherical [IF] Macro")); } break;
        // case 24: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 15-30mm F3.5-4.5 EX DG Aspherical")); } break;
        case 25: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6 APO (D) or Sigma Lens")); } break;
        // case 25: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 100-300mm F4 EX (APO (D) or D IF)")); } break;
        // case 25: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 70mm F2.8 EX DG Macro")); } break;
        // case 25: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 20mm F1.8 EX DG Aspherical RF")); } break;
        // case 25: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 30mm F1.4 EX DC")); } break;
        // case 25: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 24mm F1.8 EX DG ASP Macro")); } break;
        case 27: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 85mm F1.4 G (D)")); } break;
        case 28: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 100mm F2.8 Macro (D) or Tamron Lens")); } break;
        // case 28: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 90mm F2.8 Di Macro")); } break;
        // case 28: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 180mm F3.5 Di LD [IF] Macro")); } break;
        case 29: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 75-300mm F4.5-5.6 (D)")); } break;
        case 30: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-80mm F3.5-5.6 (D) or Sigma Lens")); } break;
        // case 30: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 10-20mm F4-5.6 EX DC")); } break;
        // case 30: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 12-24mm F4.5-5.6 EX DG")); } break;
        // case 30: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 28-70mm EX DG F2.8")); } break;
        // case 30: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 55-200mm F4-5.6 DC")); } break;
        // case 31: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 50mm F2.8 Macro (D) or F3.5")); } break;
        // case 31: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 50mm F3.5 Macro")); } break;
        case 32: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 300mm F2.8 G or 1.5x Teleconverter")); } break;
        case 33: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 70-200mm F2.8 G")); } break;
        case 35: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 85mm F1.4 G (D) Limited")); } break;
        case 36: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-100mm F3.5-5.6 (D)")); } break;
        case 38: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 17-35mm F2.8-4 (D)")); } break;
        case 39: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-75mm F2.8 (D)")); } break;
        case 40: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF DT 18-70mm F3.5-5.6 (D)")); } break;
        case 41: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF DT 11-18mm F4.5-5.6 (D) or Tamron Lens")); } break;
        // case 41: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 11-18mm F4.5-5.6 Di II LD Aspherical IF")); } break;
        case 42: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF DT 18-200mm F3.5-6.3 (D)")); } break;
        case 43: { HAN_snprintf(pText, nTextSize, TEXT("Sony 35mm F1.4 G (SAL35F14G)")); } break;
        case 44: { HAN_snprintf(pText, nTextSize, TEXT("Sony 50mm F1.4 (SAL50F14)")); } break;
        case 45: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Planar T* 85mm F1.4 ZA (SAL85F14Z)")); } break;
        case 46: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Vario-Sonnar T* DT 16-80mm F3.5-4.5 ZA (SAL1680Z)")); } break;
        case 47: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Sonnar T* 135mm F1.8 ZA (SAL135F18Z)")); } break;
        case 48: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Vario-Sonnar T* 24-70mm F2.8 ZA SSM (SAL2470Z) or Other Lens")); } break;
        // case 48: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Vario-Sonnar T* 24-70mm F2.8 ZA SSM II (SAL2470Z2)")); } break;
        // case 48: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 24-70mm F2.8 Di USD")); } break;
        case 49: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 55-200mm F4-5.6 (SAL55200)")); } break;
        case 50: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 18-250mm F3.5-6.3 (SAL18250)")); } break;
        case 51: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 16-105mm F3.5-5.6 (SAL16105)")); } break;
        case 52: { HAN_snprintf(pText, nTextSize, TEXT("Sony 70-300mm F4.5-5.6 G SSM (SAL70300G) or G SSM II or Tamron Lens")); } break;
        // case 52: { HAN_snprintf(pText, nTextSize, TEXT("Sony 70-300mm F4.5-5.6 G SSM II (SAL70300G2)")); } break;
        // case 52: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 70-300mm F4-5.6 Di USD")); } break;
        case 53: { HAN_snprintf(pText, nTextSize, TEXT("Sony 70-400mm F4-5.6 G SSM (SAL70400G)")); } break;
        case 54: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Vario-Sonnar T* 16-35mm F2.8 ZA SSM (SAL1635Z) or ZA SSM II")); } break;
        // case 54: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Vario-Sonnar T* 16-35mm F2.8 ZA SSM II (SAL1635Z2)")); } break;
        case 55: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 18-55mm F3.5-5.6 SAM (SAL1855) or SAM II")); } break;
        // case 55: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 18-55mm F3.5-5.6 SAM II (SAL18552)")); } break;
        case 56: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 55-200mm F4-5.6 SAM (SAL55200-2)")); } break;
        case 57: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 50mm F1.8 SAM (SAL50F18) or Tamron Lens or Commlite CM-EF-NEX adapter")); } break;
        // case 57: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 60mm F2 Di II LD [IF] Macro 1:1")); } break;
        // case 57: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 18-270mm F3.5-6.3 Di II PZD")); } break;
        case 58: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 30mm F2.8 Macro SAM (SAL30M28)")); } break;
        case 59: { HAN_snprintf(pText, nTextSize, TEXT("Sony 28-75mm F2.8 SAM (SAL2875)")); } break;
        case 60: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Distagon T* 24mm F2 ZA SSM (SAL24F20Z)")); } break;
        case 61: { HAN_snprintf(pText, nTextSize, TEXT("Sony 85mm F2.8 SAM (SAL85F28)")); } break;
        case 62: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 35mm F1.8 SAM (SAL35F18)")); } break;
        case 63: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 16-50mm F2.8 SSM (SAL1650)")); } break;
        case 64: { HAN_snprintf(pText, nTextSize, TEXT("Sony 500mm F4 G SSM (SAL500F40G)")); } break;
        case 65: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 18-135mm F3.5-5.6 SAM (SAL18135)")); } break;
        case 66: { HAN_snprintf(pText, nTextSize, TEXT("Sony 300mm F2.8 G SSM II (SAL300F28G2)")); } break;
        case 67: { HAN_snprintf(pText, nTextSize, TEXT("Sony 70-200mm F2.8 G SSM II (SAL70200G2)")); } break;
        case 68: { HAN_snprintf(pText, nTextSize, TEXT("Sony DT 55-300mm F4.5-5.6 SAM (SAL55300)")); } break;
        case 69: { HAN_snprintf(pText, nTextSize, TEXT("Sony 70-400mm F4-5.6 G SSM II (SAL70400G2)")); } break;
        case 70: { HAN_snprintf(pText, nTextSize, TEXT("Carl Zeiss Planar T* 50mm F1.4 ZA SSM (SAL50F14Z)")); } break;
        case 128: { HAN_snprintf(pText, nTextSize, TEXT("Tamron or Sigma Lens (128)")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 18-200mm F3.5-6.3 XR Di II LD Aspherical [IF] Macro")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 28-300mm F3.5-6.3 XR Di LD Aspherical [IF] Macro")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 28-200mm F3.8-5.6 XR Di Aspherical [IF] Macro")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 17-35mm F2.8-4 Di LD Aspherical IF")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 50-150mm F2.8 EX DC APO HSM II")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 10-20mm F3.5 EX DC HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 70-200mm F2.8 II EX DG APO MACRO HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 10mm F2.8 EX DC HSM Fisheye")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 50mm F1.4 EX DG HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 85mm F1.4 EX DG HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 24-70mm F2.8 IF EX DG HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 18-250mm F3.5-6.3 DC OS HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 17-50mm F2.8 EX DC HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 17-70mm F2.8-4 DC Macro HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 150mm F2.8 EX DG OS HSM APO Macro")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 150-500mm F5-6.3 APO DG OS HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 28-105mm F4-5.6 [IF]")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 35mm F1.4 DG HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 18-35mm F1.8 DC HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 50-500mm F4.5-6.3 APO DG OS HSM")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 24-105mm F4 DG HSM | A")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 30mm F1.4")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 35mm F1.4 DG HSM | A")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 105mm F2.8 EX DG OS HSM Macro")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 180mm F2.8 EX DG OS HSM APO Macro")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 18-300mm F3.5-6.3 DC Macro HSM | C")); } break;
        // case 128: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 18-50mm F2.8-4.5 DC HSM")); } break;
        case 129: { HAN_snprintf(pText, nTextSize, TEXT("Tamron Lens (129)")); } break;
        // case 129: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 200-400mm F5.6 LD")); } break;
        // case 129: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 70-300mm F4-5.6 LD")); } break;
        case 131: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 20-40mm F2.7-3.5 SP Aspherical IF")); } break;
        case 135: { HAN_snprintf(pText, nTextSize, TEXT("Vivitar 28-210mm F3.5-5.6")); } break;
        case 136: { HAN_snprintf(pText, nTextSize, TEXT("Tokina EMZ M100 AF 100mm F3.5")); } break;
        case 137: { HAN_snprintf(pText, nTextSize, TEXT("Cosina 70-210mm F2.8-4 AF")); } break;
        case 138: { HAN_snprintf(pText, nTextSize, TEXT("Soligor 19-35mm F3.5-4.5")); } break;
        case 139: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AF 28-300mm F4-6.3")); } break;
        case 142: { HAN_snprintf(pText, nTextSize, TEXT("Cosina AF 70-300mm F4.5-5.6 MC")); } break;
        case 146: { HAN_snprintf(pText, nTextSize, TEXT("Voigtlander Macro APO-Lanthar 125mm F2.5 SL")); } break;
        case 194: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 17-50mm F2.8 XR Di II LD Aspherical [IF]")); } break;
        case 202: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 70-200mm F2.8 Di LD [IF] Macro")); } break;
        case 203: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 70-200mm F2.8 Di USD")); } break;
        case 204: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 24-70mm F2.8 Di USD")); } break;
        case 212: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 28-300mm F3.5-6.3 Di PZD")); } break;
        case 213: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 16-300mm F3.5-6.3 Di II PZD Macro")); } break;
        case 214: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 150-600mm F5-6.3 Di USD")); } break;
        case 215: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 15-30mm F2.8 Di USD")); } break;
        case 216: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 45mm F1.8 Di USD")); } break;
        case 217: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 35mm F1.8 Di USD")); } break;
        case 218: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 90mm F2.8 Di Macro 1:1 USD (F017)")); } break;
        case 220: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 150-600mm F5-6.3 Di USD G2")); } break;
        case 224: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP 90mm F2.8 Di Macro 1:1 USD (F004)")); } break;
        case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron Lens (255)")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 17-50mm F2.8 XR Di II LD Aspherical")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 18-250mm F3.5-6.3 XR Di II LD")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 55-200mm F4-5.6 Di II LD Macro")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 70-300mm F4-5.6 Di LD Macro 1:2")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 200-500mm F5.0-6.3 Di LD IF")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 10-24mm F3.5-4.5 Di II LD Aspherical IF")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 70-200mm F2.8 Di LD IF Macro")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 28-75mm F2.8 XR Di LD Aspherical IF")); } break;
        // case 255: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 90-300mm F4.5-5.6 Telemacro")); } break;
        case 1868: { HAN_snprintf(pText, nTextSize, TEXT("Sigma MC-11 SA-E Mount Converter with not-supported Sigma lens")); } break;
        case 2550: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.7")); } break;
        case 2551: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-70mm F4 or Other Lens")); } break;
        // case 2551: { HAN_snprintf(pText, nTextSize, TEXT("Sigma UC AF 28-70mm F3.5-4.5")); } break;
        // case 2551: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 28-70mm F2.8")); } break;
        // case 2551: { HAN_snprintf(pText, nTextSize, TEXT("Sigma M-AF 70-200mm F2.8 EX Aspherical")); } break;
        // case 2551: { HAN_snprintf(pText, nTextSize, TEXT("Quantaray M-AF 35-80mm F4-5.6")); } break;
        // case 2551: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 28-70mm F2.8-4.5 AF")); } break;
        case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-85mm F3.5-4.5 or Other Lens")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 19-35mm F3.5-4.5")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 28-70mm F2.8 AT-X")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 80-400mm F4.5-5.6 AT-X AF II 840")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AF PRO 28-80mm F2.8 AT-X 280")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X PRO [II] AF 28-70mm F2.6-2.8 270")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 19-35mm F3.5-4.5")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Angenieux AF 28-70mm F2.6")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X 17 AF 17mm F3.5")); } break;
        // case 2552: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 20-35mm F3.5-4.5 II AF")); } break;
        case 2553: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-135mm F4-4.5 or Other Lens")); } break;
        // case 2553: { HAN_snprintf(pText, nTextSize, TEXT("Sigma ZOOM-alpha 35-135mm F3.5-4.5")); } break;
        // case 2553: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 28-105mm F2.8-4 Aspherical")); } break;
        // case 2553: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 28-105mm F4-5.6 UC")); } break;
        // case 2553: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X 242 AF 24-200mm F3.5-5.6")); } break;
        case 2554: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-105mm F3.5-4.5")); } break;
        case 2555: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 70-210mm F4 Macro or Sigma Lens")); } break;
        // case 2555: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 70-210mm F4-5.6 APO")); } break;
        // case 2555: { HAN_snprintf(pText, nTextSize, TEXT("Sigma M-AF 70-200mm F2.8 EX APO")); } break;
        // case 2555: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 75-200mm F2.8-3.5")); } break;
        case 2556: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 135mm F2.8")); } break;
        case 2557: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 28mm F2.8")); } break;
        case 2558: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24-50mm F4")); } break;
        case 2560: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-200mm F4.5")); } break;
        case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 75-300mm F4.5-5.6 or Sigma Lens")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 70-300mm F4-5.6 DL Macro")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 300mm F4 APO Macro")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 500mm F4.5 APO")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 170-500mm F5-6.3 APO Aspherical")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X AF 300mm F4")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X AF 400mm F5.6 SD")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AF 730 II 75-300mm F4.5-5.6")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 800mm F5.6 APO")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 400mm F5.6 APO Macro")); } break;
        // case 2561: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 1000mm F8 APO")); } break;
        case 2562: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.4 [New]")); } break;
        case 2563: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 300mm F2.8 APO or Sigma Lens")); } break;
        // case 2563: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 50-500mm F4-6.3 EX DG APO")); } break;
        // case 2563: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 170-500mm F5-6.3 APO Aspherical")); } break;
        // case 2563: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 500mm F4.5 EX DG APO")); } break;
        // case 2563: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 400mm F5.6 APO")); } break;
        case 2564: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F2.8 Macro or Sigma Lens")); } break;
        // case 2564: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 50mm F2.8 EX Macro")); } break;
        case 2565: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 APO")); } break;
        case 2566: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24mm F2.8 or Sigma Lens")); } break;
        // case 2566: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 17-35mm F2.8-4 EX Aspherical")); } break;
        case 2572: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 500mm F8 Reflex")); } break;
        case 2578: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 16mm F2.8 Fisheye or Sigma Lens")); } break;
        // case 2578: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 8mm F4 EX [DG] Fisheye")); } break;
        // case 2578: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 14mm F3.5")); } break;
        // case 2578: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 15mm F2.8 Fisheye")); } break;
        case 2579: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 20mm F2.8 or Tokina Lens")); } break;
        // case 2579: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X Pro DX 11-16mm F2.8")); } break;
        case 2581: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100mm F2.8 Macro [New] or Sigma or Tamron Lens")); } break;
        // case 2581: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 90mm F2.8 Macro")); } break;
        // case 2581: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 105mm F2.8 EX [DG] Macro")); } break;
        // case 2581: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 180mm F5.6 Macro")); } break;
        // case 2581: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 180mm F3.5 EX DG Macro")); } break;
        // case 2581: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 90mm F2.8 Macro")); } break;
        case 2585: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-105mm F3.5-4.5 New or Tamron Lens")); } break;
        // case 2585: { HAN_snprintf(pText, nTextSize, TEXT("Beroflex 35-135mm F3.5-4.5")); } break;
        // case 2585: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 24-135mm F3.5-5.6")); } break;
        case 2588: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 70-210mm F3.5-4.5")); } break;
        case 2589: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F2.8 APO or Tokina Lens")); } break;
        // case 2589: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 80-200mm F2.8")); } break;
        case 2590: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 G APO + Minolta AF 1.4x APO or Other Lens + 1.4x")); } break;
        // case 2590: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 HS-APO G + Minolta AF 1.4x APO")); } break;
        case 2591: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35mm F1.4")); } break;
        case 2592: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 85mm F1.4 G (D)")); } break;
        case 2593: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 APO")); } break;
        case 2594: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 3x-1x F1.7-2.8 Macro")); } break;
        case 2596: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28mm F2")); } break;
        case 2597: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35mm F2 [New]")); } break;
        case 2598: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100mm F2")); } break;
        case 2601: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 G APO + Minolta AF 2x APO or Other Lens + 2x")); } break;
        // case 2601: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 HS-APO G + Minolta AF 2x APO")); } break;
        case 2604: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F4.5-5.6")); } break;
        case 2605: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-80mm F4-5.6")); } break;
        case 2606: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6")); } break;
        case 2607: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-80mm F4-5.6")); } break;
        case 2608: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 300mm F2.8 HS-APO G")); } break;
        case 2609: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 HS-APO G")); } break;
        case 2612: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 HS-APO G")); } break;
        case 2613: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.7 New")); } break;
        case 2615: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-105mm F3.5-4.5 xi")); } break;
        case 2616: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-200mm F4.5-5.6 xi")); } break;
        case 2618: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-80mm F4-5.6 xi")); } break;
        case 2619: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F4.5-5.6 xi")); } break;
        case 2620: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-70mm F2.8 G")); } break;
        case 2621: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6 xi")); } break;
        case 2624: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-80mm F4-5.6 Power Zoom")); } break;
        case 2628: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F2.8 HS-APO G")); } break;
        case 2629: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 85mm F1.4 New")); } break;
        case 2631: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6 APO")); } break;
        case 2632: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24-50mm F4 New")); } break;
        case 2638: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F2.8 Macro New")); } break;
        case 2639: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100mm F2.8 Macro")); } break;
        case 2641: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 20mm F2.8 New")); } break;
        case 2642: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24mm F2.8 New")); } break;
        case 2644: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-400mm F4.5-6.7 APO")); } break;
        case 2662: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.4 New")); } break;
        case 2667: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35mm F2 New")); } break;
        case 2668: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28mm F2 New")); } break;
        case 2672: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24-105mm F3.5-4.5 (D)")); } break;
        case 3046: { HAN_snprintf(pText, nTextSize, TEXT("Metabones Canon EF Speed Booster")); } break;
        case 4567: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 70-210mm F4-5.6")); } break;
        case 4568: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AF 35-200mm F4-5.6 Zoom SD")); } break;
        case 4570: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 35-135mm F3.5-4.5")); } break;
        case 4571: { HAN_snprintf(pText, nTextSize, TEXT("Vivitar 70-210mm F4.5-5.6")); } break;
        case 4574: { HAN_snprintf(pText, nTextSize, TEXT("2x Teleconverter or Tamron or Tokina Lens")); } break;
        // case 4574: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 90mm F2.5")); } break;
        // case 4574: { HAN_snprintf(pText, nTextSize, TEXT("Tokina RF 500mm F8.0 x2")); } break;
        // case 4574: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 300mm F2.8 x2")); } break;
        case 4575: { HAN_snprintf(pText, nTextSize, TEXT("1.4x Teleconverter")); } break;
        case 4585: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 300mm F2.8 LD IF")); } break;
        case 4586: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 35-105mm F2.8 LD Aspherical IF")); } break;
        case 4587: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 70-210mm F2.8 SP LD")); } break;
        case 4812: { HAN_snprintf(pText, nTextSize, TEXT("Metabones Canon EF Speed Booster Ultra")); } break;
        case 6118: { HAN_snprintf(pText, nTextSize, TEXT("Canon EF Adapter")); } break;
        case 6528: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 16mm F2.8 Filtermatic Fisheye")); } break;
        case 6553: { HAN_snprintf(pText, nTextSize, TEXT("E-Mount, T-Mount, Other Lens or no lens")); } break;
        // case 6553: { HAN_snprintf(pText, nTextSize, TEXT("Arax MC 35mm F2.8 Tilt+Shift")); } break;
        // case 6553: { HAN_snprintf(pText, nTextSize, TEXT("Arax MC 80mm F2.8 Tilt+Shift")); } break;
        // case 6553: { HAN_snprintf(pText, nTextSize, TEXT("Zenitar MF 16mm F2.8 Fisheye M42")); } break;
        // case 6553: { HAN_snprintf(pText, nTextSize, TEXT("Samyang 500mm Mirror F8.0")); } break;
        // case 6553: { HAN_snprintf(pText, nTextSize, TEXT("Pentacon Auto 135mm F2.8")); } break;
        // case 6553: { HAN_snprintf(pText, nTextSize, TEXT("Pentacon Auto 29mm F2.8")); } break;
        // case 6553: { HAN_snprintf(pText, nTextSize, TEXT("Helios 44-2 58mm F2.0")); } break;
        case 18688: { HAN_snprintf(pText, nTextSize, TEXT("Sigma MC-11 SA-E Mount Converter with not-supported Sigma lens")); } break;
        case 25501: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.7")); } break;
        case 25511: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-70mm F4 or Other Lens")); } break;
        // case 25511: { HAN_snprintf(pText, nTextSize, TEXT("Sigma UC AF 28-70mm F3.5-4.5")); } break;
        // case 25511: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 28-70mm F2.8")); } break;
        // case 25511: { HAN_snprintf(pText, nTextSize, TEXT("Sigma M-AF 70-200mm F2.8 EX Aspherical")); } break;
        // case 25511: { HAN_snprintf(pText, nTextSize, TEXT("Quantaray M-AF 35-80mm F4-5.6")); } break;
        // case 25511: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 28-70mm F2.8-4.5 AF")); } break;
        case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-85mm F3.5-4.5 or Other Lens")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 19-35mm F3.5-4.5")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 28-70mm F2.8 AT-X")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 80-400mm F4.5-5.6 AT-X AF II 840")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AF PRO 28-80mm F2.8 AT-X 280")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X PRO [II] AF 28-70mm F2.6-2.8 270")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 19-35mm F3.5-4.5")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Angenieux AF 28-70mm F2.6")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X 17 AF 17mm F3.5")); } break;
        // case 25521: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 20-35mm F3.5-4.5 II AF")); } break;
        case 25531: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-135mm F4-4.5 or Other Lens")); } break;
        // case 25531: { HAN_snprintf(pText, nTextSize, TEXT("Sigma ZOOM-alpha 35-135mm F3.5-4.5")); } break;
        // case 25531: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 28-105mm F2.8-4 Aspherical")); } break;
        // case 25531: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 28-105mm F4-5.6 UC")); } break;
        // case 25531: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X 242 AF 24-200mm F3.5-5.6")); } break;
        case 25541: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-105mm F3.5-4.5")); } break;
        case 25551: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 70-210mm F4 Macro or Sigma Lens")); } break;
        // case 25551: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 70-210mm F4-5.6 APO")); } break;
        // case 25551: { HAN_snprintf(pText, nTextSize, TEXT("Sigma M-AF 70-200mm F2.8 EX APO")); } break;
        // case 25551: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 75-200mm F2.8-3.5")); } break;
        case 25561: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 135mm F2.8")); } break;
        case 25571: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 28mm F2.8")); } break;
        case 25581: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24-50mm F4")); } break;
        case 25601: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-200mm F4.5")); } break;
        case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 75-300mm F4.5-5.6 or Sigma Lens")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 70-300mm F4-5.6 DL Macro")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 300mm F4 APO Macro")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 500mm F4.5 APO")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 170-500mm F5-6.3 APO Aspherical")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X AF 300mm F4")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X AF 400mm F5.6 SD")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AF 730 II 75-300mm F4.5-5.6")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 800mm F5.6 APO")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 400mm F5.6 APO Macro")); } break;
        // case 25611: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 1000mm F8 APO")); } break;
        case 25621: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.4 [New]")); } break;
        case 25631: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 300mm F2.8 APO or Sigma Lens")); } break;
        // case 25631: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 50-500mm F4-6.3 EX DG APO")); } break;
        // case 25631: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 170-500mm F5-6.3 APO Aspherical")); } break;
        // case 25631: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 500mm F4.5 EX DG APO")); } break;
        // case 25631: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 400mm F5.6 APO")); } break;
        case 25641: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F2.8 Macro or Sigma Lens")); } break;
        // case 25641: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 50mm F2.8 EX Macro")); } break;
        case 25651: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 APO")); } break;
        case 25661: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24mm F2.8 or Sigma Lens")); } break;
        // case 25661: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 17-35mm F2.8-4 EX Aspherical")); } break;
        case 25721: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 500mm F8 Reflex")); } break;
        case 25781: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 16mm F2.8 Fisheye or Sigma Lens")); } break;
        // case 25781: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 8mm F4 EX [DG] Fisheye")); } break;
        // case 25781: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 14mm F3.5")); } break;
        // case 25781: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 15mm F2.8 Fisheye")); } break;
        case 25791: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 20mm F2.8 or Tokina Lens")); } break;
        // case 25791: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AT-X Pro DX 11-16mm F2.8")); } break;
        case 25811: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100mm F2.8 Macro [New] or Sigma or Tamron Lens")); } break;
        // case 25811: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 90mm F2.8 Macro")); } break;
        // case 25811: { HAN_snprintf(pText, nTextSize, TEXT("Sigma AF 105mm F2.8 EX [DG] Macro")); } break;
        // case 25811: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 180mm F5.6 Macro")); } break;
        // case 25811: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 180mm F3.5 EX DG Macro")); } break;
        // case 25811: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 90mm F2.8 Macro")); } break;
        case 25851: { HAN_snprintf(pText, nTextSize, TEXT("Beroflex 35-135mm F3.5-4.5")); } break;
        case 25858: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-105mm F3.5-4.5 New or Tamron Lens")); } break;
        // case 25858: { HAN_snprintf(pText, nTextSize, TEXT("Tamron 24-135mm F3.5-5.6")); } break;
        case 25881: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 70-210mm F3.5-4.5")); } break;
        case 25891: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F2.8 APO or Tokina Lens")); } break;
        // case 25891: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 80-200mm F2.8")); } break;
        case 25901: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 G APO + Minolta AF 1.4x APO or Other Lens + 1.4x")); } break;
        // case 25901: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 HS-APO G + Minolta AF 1.4x APO")); } break;
        case 25911: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35mm F1.4")); } break;
        case 25921: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 85mm F1.4 G (D)")); } break;
        case 25931: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 APO")); } break;
        case 25941: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 3x-1x F1.7-2.8 Macro")); } break;
        case 25961: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28mm F2")); } break;
        case 25971: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35mm F2 [New]")); } break;
        case 25981: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100mm F2")); } break;
        case 26011: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 G APO + Minolta AF 2x APO or Other Lens + 2x")); } break;
        // case 26011: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 HS-APO G + Minolta AF 2x APO")); } break;
        case 26041: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F4.5-5.6")); } break;
        case 26051: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-80mm F4-5.6")); } break;
        case 26061: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6")); } break;
        case 26071: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-80mm F4-5.6")); } break;
        case 26081: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 300mm F2.8 HS-APO G")); } break;
        case 26091: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 600mm F4 HS-APO G")); } break;
        case 26121: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 200mm F2.8 HS-APO G")); } break;
        case 26131: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.7 New")); } break;
        case 26151: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-105mm F3.5-4.5 xi")); } break;
        case 26161: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-200mm F4.5-5.6 xi")); } break;
        case 26181: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-80mm F4-5.6 xi")); } break;
        case 26191: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F4.5-5.6 xi")); } break;
        case 26201: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28-70mm F2.8 G")); } break;
        case 26211: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6 xi")); } break;
        case 26241: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35-80mm F4-5.6 Power Zoom")); } break;
        case 26281: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 80-200mm F2.8 HS-APO G")); } break;
        case 26291: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 85mm F1.4 New")); } break;
        case 26311: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-300mm F4.5-5.6 APO")); } break;
        case 26321: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24-50mm F4 New")); } break;
        case 26381: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F2.8 Macro New")); } break;
        case 26391: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100mm F2.8 Macro")); } break;
        case 26411: { HAN_snprintf(pText, nTextSize, TEXT("Minolta/Sony AF 20mm F2.8 New")); } break;
        case 26421: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24mm F2.8 New")); } break;
        case 26441: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 100-400mm F4.5-6.7 APO")); } break;
        case 26621: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 50mm F1.4 New")); } break;
        case 26671: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 35mm F2 New")); } break;
        case 26681: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 28mm F2 New")); } break;
        case 26721: { HAN_snprintf(pText, nTextSize, TEXT("Minolta AF 24-105mm F3.5-4.5 (D)")); } break;
        case 30464: { HAN_snprintf(pText, nTextSize, TEXT("Metabones Canon EF Speed Booster")); } break;
        case 45671: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 70-210mm F4-5.6")); } break;
        case 45681: { HAN_snprintf(pText, nTextSize, TEXT("Tokina AF 35-200mm F4-5.6 Zoom SD")); } break;
        case 45701: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 35-135mm F3.5-4.5")); } break;
        case 45711: { HAN_snprintf(pText, nTextSize, TEXT("Vivitar 70-210mm F4.5-5.6")); } break;
        case 45741: { HAN_snprintf(pText, nTextSize, TEXT("2x Teleconverter or Tamron or Tokina Lens")); } break;
        // case 45741: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 90mm F2.5")); } break;
        // case 45741: { HAN_snprintf(pText, nTextSize, TEXT("Tokina RF 500mm F8.0 x2")); } break;
        // case 45741: { HAN_snprintf(pText, nTextSize, TEXT("Tokina 300mm F2.8 x2")); } break;
        case 45751: { HAN_snprintf(pText, nTextSize, TEXT("1.4x Teleconverter")); } break;
        case 45851: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 300mm F2.8 LD IF")); } break;
        case 45861: { HAN_snprintf(pText, nTextSize, TEXT("Tamron SP AF 35-105mm F2.8 LD Aspherical IF")); } break;
        case 45871: { HAN_snprintf(pText, nTextSize, TEXT("Tamron AF 70-210mm F2.8 SP LD")); } break;
        case 48128: { HAN_snprintf(pText, nTextSize, TEXT("Metabones Canon EF Speed Booster Ultra")); } break;
        case 61184: { HAN_snprintf(pText, nTextSize, TEXT("Canon EF Adapter")); } break;
        case 65280: { HAN_snprintf(pText, nTextSize, TEXT("Sigma 16mm F2.8 Filtermatic Fisheye")); } break;
        case 65535: { HAN_snprintf(pText, nTextSize, TEXT("E-Mount, T-Mount, Other Lens or no lens")); } break;
        // case 65535: { HAN_snprintf(pText, nTextSize, TEXT("Arax MC 35mm F2.8 Tilt+Shift")); } break;
        // case 65535: { HAN_snprintf(pText, nTextSize, TEXT("Arax MC 80mm F2.8 Tilt+Shift")); } break;
        // case 65535: { HAN_snprintf(pText, nTextSize, TEXT("Zenitar MF 16mm F2.8 Fisheye M42")); } break;
        // case 65535: { HAN_snprintf(pText, nTextSize, TEXT("Samyang 500mm Mirror F8.0")); } break;
        // case 65535: { HAN_snprintf(pText, nTextSize, TEXT("Pentacon Auto 135mm F2.8")); } break;
        // case 65535: { HAN_snprintf(pText, nTextSize, TEXT("Pentacon Auto 29mm F2.8")); } break;
        // case 65535: { HAN_snprintf(pText, nTextSize, TEXT("Helios 44-2 58mm F2.0")); } break;

        default: { HAN_snprintf(pText, nTextSize, TEXT("Î´ÖªÐÍºÅ")); } break;
    }
}
