#ifndef HAN_PICTURE_JPEG_MAKER_NOTE_SONY_TAG_H
#define HAN_PICTURE_JPEG_MAKER_NOTE_SONY_TAG_H

#ifdef __cplusplus
extern "C" {
#endif

#include "..\..\..\..\..\HAN_PictureDef.h"

typedef enum {
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LENS_SPEC_0010,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCAL_LENGTH,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCAL_LENGTH_TELE_ZOOM,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT_SELECTED,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_MODE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_POINT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FOCUS_STATUS,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_ACTIVE_SENSOR,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_UPPER_LEFT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LEFT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LOWER_LEFT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_FAR_LEFT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_TOP_HORIZONTAL,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_NEAR_RIGHT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_CENTER_HORIZONTAL,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_NEAR_LEFT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_BOTTOM_HORIZONTAL,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_TOP_VERTICAL,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_CENTER_VERTICAL,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_BOTTOM_VERTICAL,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_FAR_RIGHT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_UPPER_RIGHT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_RIGHT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LOWER_RIGHT,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_UPPER_MIDDLE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_AF_STATUS_LOWER_MIDDLE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_QUALITY,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FLASH_EXPOSURE_COMP,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_TELECONVERTER,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE_FINE_TUNE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_WHITE_BALANCE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_UNKNOWN,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_TEMPERATURE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_LEVEL,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_VOLTAGE1,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_VOLTAGE2,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_0116,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BATTERY_STATE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_EXPOSURE_PROGRAM,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MODE_DIAL_POSITION,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MEM_CARD_CFG,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CAMERA_ORIENTATION,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_RATING,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CONTRAST,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_SATURATION,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_SHARPNESS,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_BRIGHTNESS,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LONG_EXPOSURE_NOISE_REDUCTION,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HIGH_ISO_NOISE_REDUCTION,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_HDR,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_MULTI_FRAME_NOISE_REDUCTION,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_COLOR_TEMPERATURE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_COLOR_COMPENSATION_FILTER,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_SCENE_MODE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_ZONE_MATCHING,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_DYNAMIC_RANGE_OPTIMIZER,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_IMAGE_STABILIZATION_B026,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LENS_TYPE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_COLOR_MODE,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_LENS_SPEC_B02A,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTION,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_FACE_DETECTED,
    PICTURE_JPEG_MAKER_NOTE_SONY_TAG_CNT,
} PICTUREJPEGMAKERNOTESONYTAG;

HANPCSTR GetJpegMakerNoteSonyTagName(PICTUREJPEGMAKERNOTESONYTAG eName);
HANPCSTR GetJpegMakerNoteSonyTagAFPointSelectedName(uint8_t cSelect);
HANPCSTR GetJpegMakerNoteSonyTagFocusModeName(uint8_t cMode);
HANPCSTR GetJpegMakerNoteSonyTagAFPointName(uint8_t cPoint);
HANPCSTR GetJpegMakerNoteSonyTagFocusStatusName(uint8_t cPoint);
HANPCSTR GetJpegMakerNoteSonyTagQualityName(uint32_t cQuality);
HANPCSTR GetJpegMakerNoteSonyTagTeleconverterName(uint32_t cTeleconverter);
HANPCSTR GetJpegMakerNoteSonyTagWhiteBalanceName(uint32_t cWhiteBalance);
HANPCSTR GetJpegMakerNoteSonyTagImageStabilizationName(uint32_t cStab);
HANPCSTR GetJpegMakerNoteSonyTagModeDialPositionName(uint32_t cPosition);
HANPCSTR GetJpegMakerNoteSonyTagMemoryCardConfigurationName(uint32_t cCfg);
HANPCSTR GetJpegMakerNoteSonyTagCameraOrientationName(uint32_t cOrientation);
HANPCSTR GetJpegMakerNoteSonyTagLongExposureNoiseReductionName(uint32_t cLongExposureNoiseReduction);
HANPCSTR GetJpegMakerNoteSonyTagHighISONoiseReductionName(uint16_t cHighISONoiseReduction);
HANPCSTR GetJpegMakerNoteSonyTagHDRValue0Name(uint16_t cHDR0);
HANPCSTR GetJpegMakerNoteSonyTagHDRValue1Name(uint16_t cHDR1);
HANPCSTR GetJpegMakerNoteSonyTagMultiFrameNoiseReductionName(uint32_t cMultiFrameNoiseReduction);
HANPCSTR GetJpegMakerNoteSonyTagFaceDetectionName(uint8_t cFaceDetection);
HANPCSTR GetJpegMakerNoteSonyTagFaceDetectedName(uint8_t cFaceDetected);

#ifdef __cplusplus
}
#endif

#endif
